### ISSUE TITLE
coordinates / info / gxp

### ISSUE THREAD

**Issue by SamSueTK** [Spegeli/PokemoGoBot-GottaCatchEmAll#100]
Hi Great job!

1 - I can not added coordinates, "can not be converted to an instance of type" double ".

2 - gpx files are no longer working?

3 - The message "Info: ..." is something real? Because always indicates places in NY

again, great job ... keep it up﻿

**Comment by wesyr** [comment]
1. change delimeter to comma ( , )
2. Can't check because of server failures ;)
3. PTC servers are failing from about an hour and that is why you get that message

**Comment by SamSueTK** [comment]
:S  Unhandled data in GPX file, attempting to skip.

**Comment by wesyr** [comment]
Same issue mate, change dot (.) in gpx to comma (,) :)

**Comment by SamSueTK** [comment]
I switched and now he does not think the file ..[21:28:28] Could not find file 'C:\Users\PauloR\Desktop\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Console\bin\Debug\Poketrack,gpx'. from mscorlib

**Comment by wesyr** [comment]
what are you writing in "GPXFile" ? you should write only "Poketrack.gps" <- don't change this dot to comma it's file extension, you need to change to dot IN the file, open it with notepad++ and change the coords dot -> comma, and also delete meta tag section as it's written in here -> https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#gpx-pathing-setup

**Comment by SamSueTK** [comment]
ai ... now does not happen any more after

[22:17:48] Export Player Infos and all Pokemon to "\Export\PokeList.csv"

**Comment by SamSueTK** [comment]
I tried gpx files that come with the program and also not worked

**Comment by Spegeli** [comment]
Please send me the complete log file and the content from the GPX file your using: http://pastie.org/pastes/new

**Comment by SamSueTK** [comment]
http://pastie.org/10921113

**Comment by Spegeli** [comment]
Ok the GPX seems but, so i dont know what is going wrong...hmmm

**Comment by SamSueTK** [comment]
You can send me a .gpx file  for me to test?

**Comment by Spegeli** [comment]
please beware this farming location is in germany: http://www.filedropper.com/gpxfile

**Comment by XiCynx** [comment]
You can also try my gpx file, this is confirmed working as I used it many times.

[Pokestop_LA_HarborCollege.zip](https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/files/389521/Pokestop_LA_HarborCollege.zip)

**Comment by Spegeli** [comment]
I uploaded a new version which use now "CultureInfo.InvariantCulture" to convert the coords to the right format like:
````
Convert.ToDouble(trk.Ele, CultureInfo.InvariantCulture)
````
i hope this finaly fix the comma and dot issue.

**Comment by SamSueTK** [comment]
ich hoffe auch :P

**Comment by SamSueTK** [comment]
Spegeli ... same issue : /

**Comment by resthavens** [comment]
sorry i'm new in this area..can i asked what is GPX file? and how to use it?

**Comment by wesyr** [comment]
@resthavens i know it will be rude, but mate... just fckn google it "GPX file", this exact thing ;)

**Comment by smou147** [comment]
Hello with me always comes the error :
( ERROR ) Please change first Latitude and / or Longitude Because currently using your default values ​​!

**Comment by XiCynx** [comment]
@SamSueTK From what I was able to see from your logs a while back, it looks like you never changed all the periods in the .GPX file to commas.  Everything I outlined and highlighted needs to be changed to a comma for the GPX file to work for you.  Or you can create your own GPX file using tutorials out there.

![3girrfu](https://cloud.githubusercontent.com/assets/20632191/17532103/f9f205bc-5e4c-11e6-9bb2-e2f6984401e7.png)

**Comment by Spegeli** [comment]
Should be solved with the latest version:
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/6a691f238dc59b353012573f48bb776b3e1aea11

The GPX File must now contains DOTS.

When anyone get still GPX issues, pls reopen a new Ticket and link to this Ticket here.
