### ISSUE TITLE
[ISSUE ACCEPTED] TransferPokemonKeepDuplicateAmount Exception Error

### ISSUE THREAD

**Issue by XiCynx** [Spegeli/PokemoGoBot-GottaCatchEmAll#101]
I set the setting to 0 and it kept throwing an exception after every transfer of a Pokemon. It never did this when I had it set to 1 or higher. The information attached it straight from the Log File minus my account information which I removed. It repeated this 80 times until all my Pokemon were transferred.

[TransferPokemonKeepDuplicateAmount_Error.txt](https://github.com/Spegeli/Pokemon-Go-Rocket-API/files/386597/TransferPokemonKeepDuplicateAmount_Error.txt)

**Comment by baransel** [comment]
I also confirm this bug. Problem is in Logic.cs line 489. After transfer, logger tries to print  stats of bestPokemonOfType. But this variable is null. I fix on my local and printed "Best NONE" when there is no same type pokemon.

**Comment by netti1337** [comment]
how to fix?

**Comment by Spegeli** [comment]
Please try the latest Version and let me know if this error still exists,

**Comment by Spegeli** [comment]
Seems to be fixed with the current version.
