### ISSUE TITLE
Set False on UsePokemonToNotTransferList

### ISSUE THREAD

**Issue by evonly** [Spegeli/PokemoGoBot-GottaCatchEmAll#106]
I have too many low CP Snorlaxs or Dragonites, want to auto transfer it but bot doesn't transfer them.

**Comment by XiCynx** [comment]
Paste a screenshot of your UserSettings in VB for us to give us more to go off of.

**Comment by evonly** [comment]
http://puu.sh/qgApf/852d45ca91.png

**Comment by Spegeli** [comment]
Yeah because you use the KeepAboveCP and KeepAboveIV Settings.

**Comment by evonly** [comment]
It keep Snorlax with 8x CP and <1000 CP @@

**Comment by XiCynx** [comment]
They may have above 90% IV, it's hard to tell on our end but it's definitely something in the settings that is preventing the bot from transferring them.

**Comment by evonly** [comment]
okay, I will try to test again. Thank for response ^^

**Comment by evonly** [comment]
I know problem here, seem it transfer all IV below 85, keep above. It doesn't save my setting to work.
http://puu.sh/qgCJh/e781a6861a.png. Just catch 5 Snorlax and 4 of them has under 85 IV.

**Comment by XiCynx** [comment]
Hmm, that is interesting.  I haven't been home in the last day and a half to try the latest version.  But I do have to ask (not wanting to get off track), where in the WORLD are you getting all them Snorlax at?

**Comment by evonly** [comment]
I join discord chat and simply just get them all :D

**Comment by Spegeli** [comment]
You Settings say: Not Transfer above IV 90, and on your screen there are all over 90, except 2.

**Comment by evonly** [comment]
There is under 90. I will make more clear sreenshot http://puu.sh/qgDsd/42cae73172.png and this too http://puu.sh/qgDsE/dca7d61c15.png

**Comment by Spegeli** [comment]
Your IV Settings is 90, and ALL your Snorlax  are above 90, except the 2.

**Comment by makejohn** [comment]
Hello, first thank you for your job! that's really awsome!
I have some problem it always shows that"(ATTENTION) Your desired destination is 52.189483232118135, -2.224109172821045 your location is 52.1898919768184, -2.22463359570228"
some time it will stop work until I pressing space

**Comment by XiCynx** [comment]
Please start a new issue and don't hijack someone else's thread.  This causes confusion and creates clutter.

**Comment by makejohn** [comment]
<img width="727" alt="default" src="https://cloud.githubusercontent.com/assets/20690567/17192678/6d18d7c4-5447-11e6-9e23-c967009f13a4.png">

**Comment by makejohn** [comment]
<img width="1280" alt="2" src="https://cloud.githubusercontent.com/assets/20690567/17192715/987ca65c-5447-11e6-8317-97291034a47e.png">

**Comment by XiCynx** [comment]
That's normal, there is nothing going wrong with your bot.

**Comment by makejohn** [comment]
OK THANK YOU!
But some time my pokemon will full, and i need to transfer some pokemon by myself
how can I solve this problem

**Comment by tahabf** [comment]
same problem makejohn somebody help
