### ISSUE TITLE
Separate log for top 10 highest CP/IV stats and update that based on interval time.

### ISSUE THREAD

**Issue by trana315** [Spegeli/PokemoGoBot-GottaCatchEmAll#11]
Very helpful if you want go into Nox and get rid of those 1k cp + but wonder if they have good IV to keep or not.

**Comment by Spegeli** [comment]
Will take a look later the day.

**Comment by rokuon** [comment]
okok so,
Instead of 10 best IV/CP, the whole complete list of pokemon owned with IV/CP by command input~~
so that anytime we can check list of our pokemon name a-z or number based with complete IV/CP details

**Comment by Kongolan** [comment]
Don't think we need this at all. Why would you like to have high CP pokemon with crap IV stats?? It's only for the beginning useful, but no valuable information for later botting.

**Comment by rokuon** [comment]
@Kongolan getting perfect IV isnt easy coz takes time, some ppl wud like to use their available high IV ones.

**Comment by Kongolan** [comment]
I currently use a IV cap of 80% and my own coded function, so it only saves pokemon with 450 CP+ if they have good IV stats and not all trash IV pokemon. All pokemon above 1100 CP are also held, though all of them have good IV. After 2 days, i have more than enough of good IV AND good CP, but crappy movesets.

**Comment by Spegeli** [comment]
With the latest version: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/806009cb6d4da6183b12235e7caa9cc2e28b68b3
there is now a option to export all infos every x minutes to csv file.
