### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by tahabf** [Spegeli/PokemoGoBot-GottaCatchEmAll#110]
How can i fix this problem? I've 9 nidorans .Some of them are below 350 cp but bot is not sending them and my duplicate amount is 3. So what can i do to solve it ?

KeepMinIVPercentage=85
KeepMinCP=350
TransferPokemonKeepDuplicateAmount=3

**Comment by Spegeli** [comment]
How many nidorans do you have? Whats there IV & CP?

**Comment by hijackem** [comment]
I have the same issue (more detailed): #140

**Comment by XiCynx** [comment]
@tahabf Do you have the NotTransferPokemonsThatCanEvolve option set to True?  If so, I believe this is why the nidoran aren't transferring, because they can evolve.
