### ISSUE TITLE
modify KeepDuplicates

### ISSUE THREAD

**Issue by hpbaxx** [Spegeli/PokemoGoBot-GottaCatchEmAll#132]
Is it possible to set two "keep duplicates" for the following?
- >minIV and/or >minCP (KeepDuplicateAmount1)
- <minIV and/or <minCP (KeepDuplicateAmount2)

example: KeepDuplicateAmount1 to 5 and KeepDuplicateAmount2 to 0
so it transfers all but 5 with >minIV and/or >minCP,
but transfers all that neither match minIV nor minCP

**Comment by Spegeli** [comment]
See https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/98
