### ISSUE TITLE
[REQUEST ACCEPTED] GPXIgnorePokestops / GPXIgnorePokemon Options for GPXPathing function

### ISSUE THREAD

**Issue by Trub47** [Spegeli/PokemoGoBot-GottaCatchEmAll#137]
A mode where the bot don´t collect any pokestops or pokemon would be nice. So it´s easier to bread a lot of eggs without getting so many xp/pokemon/stuff.

**Comment by Spegeli** [comment]
what? sorry i dont absolutly not understand what you mean ^^

**Comment by DreameR321** [comment]
He want a mode where the bot only walks around to breading eggs / he dont want that the bot catch Pokemon or farm stops i think

**Comment by XiCynx** [comment]
@Trub47 You can do this already with a custom GPX route that does not visit any Pokestops and just add all 151 Pokemon to the Do Not Catch List.  Set your walk speed to 20 and just have your route walk a very very long straight line for best results.  Nothing special needs to be done to code this into the bot.

**Comment by Spegeli** [comment]
i'm now afk, when i'm back i will take a look if i can add "GPXIgnorePokestops" "GPXIgnorePokemon".
So GPX pathing can be used without using Pokestops and catching Pokemon.

**Comment by Spegeli** [comment]
Ok added both options to the next release. 
I will inform when it's uploaded.

**Comment by Spegeli** [comment]
Uploaded new Version which includes now both functions (configurable via UserSettings)
