### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by Eurickz** [Spegeli/PokemoGoBot-GottaCatchEmAll#138]
Dear Spegeli and others Developer,

i'm a newcomer in this thing
My computer doesnt know how to open "PokemonGo.RocketAPI.Console" 
What should I install first for Visual C# Project file (.csproj)?
Sorry for my lack of knowledge

Thank you in advance

**Comment by sonnh58** [comment]
i need to download visual studio 2015 then Build it

**Comment by XiCynx** [comment]
https://www.visualstudio.com/post-download-vs?sku=community&clcid=0x409&downloadrename=true
