### ISSUE TITLE
cathchFlee

### ISSUE THREAD

**Issue by iku747** [Spegeli/PokemoGoBot-GottaCatchEmAll#141]
The new bot seems to be unable to catch any pokemon, before the last patch it worked 100%. It's just me?

**Comment by XiCynx** [comment]
CatchFlee means that you are softbanned.

**Comment by XiCynx** [comment]
Are you getting items though?  It always says you get xp, but I bet you it's picking up no items.

**Comment by iku747** [comment]
yeh it is taken objets and xp, and it take some pokemos but like just 1 succes of 30 trys

**Comment by executor819** [comment]
TransferPokemonKeepAboveIVPercentage = 70
TransferPokemonKeepAboveCP = 1500
WalkingSpeedInKilometerPerHour = 150
UsePokemonToNotCatchList= False
PrioritizeIVOverCP = False
MaxTravelDistanceInMeters = 4000
UseLuckyEggs = False
NotTransferPokemonsThatCanEvolve=False
EvolveOnlyPokemonAboveIV = False
EvolvePokemon=True
EvolveOnlyPokemonAboveIV = 95
TransferPokemon=True
TransferPokemonKeepDuplicateAmount=2 or 5 if u have much high cp 3-5 same poke
UseTransferPokemonKeepAboveCP=False
UseTransferPokemonKeepAboveIV=False
UsePokemonToNotTransferList=True
 UseIncense=False


u nevercatchflee this my best set

**Comment by XiCynx** [comment]
@iku747 Can you provide a screenshot of your command window showing this for me?

**Comment by iku747** [comment]
![example jpge](https://cloud.githubusercontent.com/assets/20708549/17222824/561192f6-54fa-11e6-96c2-37e041d98ff4.png)

**Comment by iku747** [comment]
its basically like this all time

**Comment by XiCynx** [comment]
Have you noticed if the Pokemon that flee are always of a really low CP?  I noticed this in the past but this may be something @Spegeli will have to look at.  I don't know if this is anything he can control and is just bad luck in the game.

**Comment by iku747** [comment]
Well, after 6 hours i think all was a soft ban, now i'm catching pokemons normally. Maybe ti was sometime of softban that goes wrong.

**Comment by ladymPokeD** [comment]
@iku747 Reduce WalkingSpeedInKilometerPerHour seems to be fine. 80km/hr
