### ISSUE TITLE
BadAuthentification

### ISSUE THREAD

**Issue by Tempritscher** [Spegeli/PokemoGoBot-GottaCatchEmAll#143]
I got following error. what can i do?

http://image.prntscr.com/image/433ddc44371845058cb0ddc11536baa5.png

**Comment by JuztSam** [comment]
Get the new update. 
And in UserSettings.Settings
![ff](https://cloud.githubusercontent.com/assets/20705832/17223127/8d6b1406-54fb-11e6-8e09-a03568a3c598.png)
Scroll down and you will see "GoogleUsername" and "GooglePassword" Fill in ur Email & Password
And save it and run the console and there u go! :)

**Comment by XiCynx** [comment]
@Tempritscher You coordinates are incorrect.  Make sure you are using the Period Delimiter.  Replace the comma in your coords with a period.

**Comment by XiCynx** [comment]
@JuztSam Is correct on this.

**Comment by billybrr** [comment]
can you post a download for the new version? I downloaded it and there is no .exe to run the program.

**Comment by Tempritscher** [comment]
@billybrr http://ul.to/c0bgscfb
