### ISSUE TITLE
Request: Remove softban automatically

### ISSUE THREAD

**Issue by chakuze** [Spegeli/PokemoGoBot-GottaCatchEmAll#144]
Hey,
if you teleport somewhere far (e.g. GER -> USA) you will get soft banned for a couple of hours. Solution is to go to a pokestop of your choice, spin in (you won't get anything), leave the pokestop and spin the same pokemon again directly. continue for 30-40 times and the ban is removed! (tested today multiple times). It might be necessary to build this with a little delay in between because in my opinion everytime the little pokeball loading indicator is shown the game really "registers" the spin.

Would be super cool if the bot could do it automatically when it doesn't get any items from pokestop if spinning.

**Comment by AncientGen** [comment]
softbans take about 1-90 minutes. gg on spinning the pokestop over and over.
But by the time you looted, the ban simply got lifted.

**Comment by A6uh** [comment]
@AncientGen I thought he was full of it as well. I pulled a macroing tool and it definitely works! Traveled to AUS from USA (this would normally give me a 3 hour softban, I've timed it) but was able to lift the ban within 10 minutes. That method actually does work.

**Comment by AsmoAeon** [comment]
Kinda dangerous method. I suspect that a lot of niantic's checks are turned off at the moment cause of server load issues. After a while they will turn them back on again and maybe even add more. Plus after a number of softbans it becomes permanent.

**Comment by Spegeli** [comment]
Added Anti-Softbann to the latest Version ;-)

I always recommend to not change the location to much. I change my location 1-2 per weeks.
