### ISSUE TITLE
Navigation in Logic.cs

### ISSUE THREAD

**Issue by Mikeez** [Spegeli/PokemoGoBot-GottaCatchEmAll#145]
I have not looked through the whole code. However, when we have a coordination in LastCord.ini and we Re-build the solution with a default coordination. The bot is suppose to throw a message, outside defined radius and walk to the default target.

You added that if Pokestop are found to start walking there?

Or how do I make my char walk to the default value without GPX?

**Comment by Spegeli** [comment]
The Default Cords in UserSettings are the middle of your Farming Area. With MaxTravelDistanceInMeters you can define the radius for the farming area.

When you restart the Bot, he will always continue with the Last Cords from the LastCoords.ini.
So when you change the farming area completly, remove the LastCoords.ini so he can create a new one.
