### ISSUE TITLE
Cannot add coordinates because of "," and with "." doesn't start.

### ISSUE THREAD

**Issue by cr1smc** [Spegeli/PokemoGoBot-GottaCatchEmAll#146]
https://gyazo.com/c5b18c6dc376a8b54c48d26aefa8b11d

**Comment by hijackem** [comment]
It should work if you replace the point with a comma (for me this solved this issue)

**Comment by cr1smc** [comment]
if you look closer you can see this is a comma , and don't work with it

**Comment by XiCynx** [comment]
I got that error every time I had a comma in my coordinates.  I replaced it with a period and then things worked like a charm.  Did you try that?

**Comment by XiCynx** [comment]
@cr1smc Please try the latest release and let us know if the issue still persists.

**Comment by cr1smc** [comment]
I tried , is the same thing..

**Comment by Spegeli** [comment]
It MUST work with Comma OR dots.
