### ISSUE TITLE
[SUGGEST] Make spesific pokemon exceptions

### ISSUE THREAD

**Issue by hsizadam** [Spegeli/PokemoGoBot-GottaCatchEmAll#147]
I mean, can you make Cp and Value spesific "not to transfer" thing?

i dont want to transfer all my eeves and keep 500+ three eeves or i want to keep 3 magikarps %95 IV 150+ CP.
Could you do it guys? Cause its transfering all low cp or IV but i want to make it more spesific. I want to keep 3 eeve but keep one other other pokemons.

**Comment by XiCynx** [comment]
You can set what pokemon you don't want to transfer in this list.  ALL pokemon that are on this list will take precedence over the UserSettings settings.

\PokemonGo.RocketAPI.Console\bin\Debug\Settings\PokemonsToNotTransfer.ini

**Comment by Spegeli** [comment]
Currently its not planned to make the values pokemon typ specific, sorry.
