### ISSUE TITLE
start bot

### ISSUE THREAD

**Issue by lnkakalink** [Spegeli/PokemoGoBot-GottaCatchEmAll#152]
hi all 
i am start bot and bot farm pokemons and more 
go location and 

[00:01:02] (ERROR) System.Threading.Tasks.TaskCanceledException: Отменена задача.
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:строка 36
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:строка 17
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:строка 35
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:строка 40
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PoGo.NecroBot.Logic.Navigation.<HumanLikeWalking>d__3.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Navigation.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:строка 77
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:строка 42
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:строка 34

**Comment by MalboroGmod** [comment]
[23:06:25] (ERROR) InvalidResponseException from HttpClientExtensions.cs
[23:06:25] Specified argument was out of the range of valid values.
Parameter name: index from Google.Protobuf
[23:06:25] (ERROR) InvalidResponseException from getCachedInventory
[23:06:25] Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseExce
ption' was thrown. from PokemonGo.RocketAPI.Logic
[23:06:25] (ERROR) Got an exception, trying automatic restart..

**Comment by lnkakalink** [comment]
How to turn it on automatic restart

**Comment by XiCynx** [comment]
@lnkakalink It's built in, you don't have to enable it.

**Comment by lnkakalink** [comment]
no i am click enter and start bot because not start  automatic

**Comment by lnkakalink** [comment]
![syyqhyvuv0m8dsol8onvjq 1](https://cloud.githubusercontent.com/assets/5696232/17229960/979a7878-5522-11e6-9223-15acc7b1aac4.jpg)

**Comment by XiCynx** [comment]
dude... You're using NecroBot or FoxRev, go to their fork and get assistance, we aren't forking off of them anymore.

C:\Users\tvgfx\Documents\Pokemon Go Bot\**FeroxRev**\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:строка 36
C:\Users\tvgfx\Documents\Pokemon Go Bot\**FeroxRev**\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:строка 35
C:\Users\tvgfx\Documents\Pokemon Go Bot\**PoGo.NecroBot.Logic**\State\FarmState.cs:строка 42
C:\Users\tvgfx\Documents\Pokemon Go Bot\**PoGo.NecroBot.Logic**\State\StateMachine.cs:строка 34
