### ISSUE TITLE
[ATTENTION] InvalidResponseException from HttpClientExtension

### ISSUE THREAD

**Issue by deryoshi** [Spegeli/PokemoGoBot-GottaCatchEmAll#154]
Getting this error after a few minutes. Is it just the google connection? The bot doesnt continue to run after that error. 

`Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: index from Google.Protobuf
[23:08:42] (ERROR) InvalidResponseException from getCachedInventory
Unhandled exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Logic.Inventory.<getCachedInventory>d__18.MoveNext() in G:\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Logic\Inventory.cs:Zeile 278.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`

**Comment by Penple03** [comment]
Also getting this. Though http://ispokemongodownornot.com says that only PTC is affected.

**Comment by PocaBBQ** [comment]
![image](https://cloud.githubusercontent.com/assets/16146966/17229728/33c3fb8c-5543-11e6-8eb4-0db4e55cba02.png)

i got this error too.
it happen around 30m ~ 2hrs after running script.

**Comment by cr1smc** [comment]
Got this error too...

**Comment by deryoshi** [comment]
got this error on 6 google accounts

**Comment by ladymPokeD** [comment]
google login now? or just the bot?

**Comment by ladymPokeD** [comment]
[14:34:24] (INFO) Found 23 Pokemon for Transfer:
[14:34:24] (ERROR) InvalidResponseException from HttpClientExtensi
[14:34:24] Specified argument was out of the range of valid values
Parameter name: index from Google.Protobuf
[14:34:24] (ERROR) InvalidResponseException from getCachedInventor
[14:34:24] Exception of type 'PokemonGo.RocketAPI.Exceptions.Inval
[14:34:24] (ERROR) Got an exception, trying automatic restart..

**Comment by XiCynx** [comment]
Line 279 is the following code
` Directory.CreateDirectory(export_path)`

This seems like there is an issue with something regarding the bot trying to create a folder.  Can you try running the bot as Administrator and see if that gives it the permissions needed to create the directory it needs?

**Comment by Spegeli** [comment]
Yeah its the fucking getinventory issue.
I'm lookin at this ^^

**Comment by digitalpigUK** [comment]
![capture](https://cloud.githubusercontent.com/assets/9292739/17230388/e650c576-5513-11e6-80de-21e84c8c9643.PNG)

**Comment by digitalpigUK** [comment]
![capture](https://cloud.githubusercontent.com/assets/9292739/17230462/33a228ec-5514-11e6-82ce-a389471ae0d1.PNG)

Running in admin mode, worked flawless for about 3 hours and now just throws the above each login attempt.  (great work though)

**Comment by CheatSupport** [comment]
@digitalpigUK how do you run in admin?

**Comment by Penple03** [comment]
@CheatSupport Run Visual Studio as admin / run the compiled binary.

**Comment by XiCynx** [comment]
@digitalpigUK If you are running Spegeli's bot, why do all of your errors show them coming from PoGo.NecroBot.logic?  This isn't in his code at all.  Looks like you're running another bot in my opinion.

**Comment by CYCOABHI** [comment]
Nigger this isnt Spegeli's bot.. YOU'RE A FRAUD!

**Comment by CheatSupport** [comment]
Managed to log in..
but now this:

[22:43:23] ----------------------------
[22:43:23] (INFO) Loading Settings File: "PokemonsToNotTransfer.ini"
[22:43:23] (INFO) Loading Settings File: "PokemonsToNotCatch.ini"
[22:43:23] (INFO) Loading Settings File: "PokemonsToEvolve.ini"

Nothing, it just stays on that

**Comment by KnightMirko** [comment]
Seems that I'm getting the same bug:
Exception thrown: 'System.ArgumentOutOfRangeException' in Google.Protobuf.dll
Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll

**Comment by Spegeli** [comment]
Ok it seems this is a general issue with the API.
Because Necrobot has this issues too. Maybe Niantic changed something.

**Comment by MadeBySaints** [comment]
im having the same issue as well I'm on top of this page for new content - keep up the awesome work!

**Comment by Penple03** [comment]
@Spegeli Do you think this has anything to do with the Google login change?

**Comment by MadeBySaints** [comment]
@Penple03 it cant be, because i used the new login system for about 8 hours before this happened to me

**Comment by Penple03** [comment]
@MadeBySaints Huh, I have been using the old system, and it has been working fine until an hour ago.

**Comment by MadeBySaints** [comment]
@Penple03 when @Spegeli updated this repo about 8 hours ago, i downloaded it, and i compiled without issue, even changed a few things to better suit the logger, and it worked amazing up until about an hour and a half ago. now this repo wont work because of this issue, and it seems like EVERYONE is having it. That being said i did use this very updated repo, and it worked fine most of the day. I'm thinking Niantic changed something

**Comment by Uwenator** [comment]
First of all thanks Spegeli for your work, me and many others appreciate what you did for us. 

I believe there are server issues because I got this error 2 days ago and after the server were stabilize it worked fine.

Take your time, make yourself a drink and chill and than if you want to look at the problem and fix it, but don't rush it because Internet kids these days are... Well you know I mean.. Do this and THIS

Keep up the great work !

**Comment by Sterling674** [comment]
Yeah fairly sure Niantic changed something unfortunately, thanks for all the help with this issue and hopefully it gets resolved.

**Comment by Spegeli** [comment]
```
Necronomicon - Heute um 00:07 Uhr
@everyone Current Status: An API change has destroyed all Bots right now. No, that doesn't mean you are getting banned. We have to wait on @Ferox to make the Changes.
```

So everything is said...

**Comment by CheatSupport** [comment]
Thanks for your hard work. Hopefully it will all be resolved soon!

**Comment by balput** [comment]
yeah dude, thanks for it, and take your time to fix it :+1:

**Comment by Mrbeyond13** [comment]
![default](https://cloud.githubusercontent.com/assets/20706542/17231514/6f79dc10-5533-11e6-94c8-ff5025391370.png)

It's trying to live with unstoppable reconnects

**Comment by umbralogix** [comment]
Ferox seems to have fixed the API

https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/62#issuecomment-236040042

**Comment by Spegeli** [comment]
@umbralogix no its not fixed yet

**Comment by truepokegod** [comment]
thought it was just me :|

**Comment by MadeBySaints** [comment]
@umbralogix just because he got it fixed in his bot, doesnt mean he has committed the code yet. Theres still a process for all that. Be patient :)

**Comment by umbralogix** [comment]
@MadeBySaints I realize, I was just referencing the issue to make people aware that a fix is being implemented.

**Comment by truepokegod** [comment]
gona go play forreal outside while the issue gets fixed. :D

**Comment by Spegeli** [comment]
This issue is very weird.
Currently i talk with Necro, he mean that Necro 0.1.7 is working, but 0.1.8 and 0.1.9 not, so some of the think that this is a Logic Part issue.
But my Fork still use the old API and we have this issue too.

**Comment by Ar1i** [comment]
Same Problem here Spegeli. I am looking into it too tho.

**Comment by poccix** [comment]
Seems to be a problem with the amount of requests in short time - i think.

**Comment by Spegeli** [comment]
Ok seems this little delays solves the problem ^^

**Comment by umbralogix** [comment]
@poccix I've heard reports from pogodev subreddit that traffic exceeding ~3 requests per second are getting timed out/throttled at the moment.

**Comment by IstenesImre** [comment]
Please, make a build with delay patch!

**Comment by Spegeli** [comment]
@IstenesImre no wait...i will remove my fork instead -_-

unbelivabel what some user thing...

**Comment by A6uh** [comment]
Works Beautifully.

**Comment by balput** [comment]
so is this fixed yet ? how to fix, cause im a noob, please guide me so i can fix it, thanks

**Comment by evonly** [comment]
@Spegeli I tried the version 3 days ago, which still use configs folder instead of settings folder. It is working so fine atm.

**Comment by Napcazz** [comment]
Can you make same fix for old version too ?

**Comment by Spegeli** [comment]
@balput maybe you should take a look on the wiki.
@Napcazz let me think about it....aaahhmm no

**Comment by ladymPokeD** [comment]
There is still error. like farming 10 sec and getting an error

**Comment by Mrbeyond13** [comment]
Works great, thanks:**

**Comment by umbralogix** [comment]
Working fine for me. Will update with error if it crashes.

**Comment by Crankers** [comment]
Lol as soon as i got mine working, i see your update

**Comment by Crankers** [comment]
Thanks

**Comment by Spegeli** [comment]
It can happen does this issue randomly appears anyway.
Maybe i need to adjust this delay a little more.

**Comment by ladymPokeD** [comment]
I tried to reduce the km/hr to 65. it seems to work much better.

**Comment by cr1smc** [comment]
Works good , thanks XD

**Comment by balput** [comment]
@Spegeli oh sry it was my bad after all, im still using the old version, and now im trying to find the new version

**Comment by Crankers** [comment]
//I used

 System.Random rnd = new System.Random();
int number = rnd.Next(200, 500);
System.Threading.Thread.Sleep(number);

**Comment by Crankers** [comment]
//Logger.Write($"Requesting {typeof(TResponsePayload).Name}", LogLevel.Debug);
            Debug.WriteLine($"Requesting {typeof(TResponsePayload).Name}");

            //Set Timeout
            System.Random rnd = new System.Random();
            int number = rnd.Next(200, 500);
            System.Threading.Thread.Sleep(number);

            var response = await PostProto<TRequest>(client, url, request);

**Comment by justwerelax** [comment]
@Spegeli hi spegeli . im new . i dont see ur bot link . can u help me ? :/

**Comment by balput** [comment]
btw, can i get the link to download the new version ? please :(

**Comment by justwerelax** [comment]
@balput me too

**Comment by Mrbeyond13** [comment]
@balput @justwerelax  
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll <<<<<<

**Comment by justwerelax** [comment]
@Mrbeyond13  where is exe ? idont see anywhere

**Comment by firrae** [comment]
@balput and @justwerelax there are no pre-built executables, you're gonna need to learn how to compile it

**Comment by Crankers** [comment]
set  "PokemonGo.RocketAPI.Console" as startup project

**Comment by IstenesImre** [comment]
eh.. yep.. install windows, install visualstudio, install .net framework... aaaaand you can build..

**Comment by justwerelax** [comment]
@firrae @Crankers @IstenesImre @Mrbeyond13  ok i try it now and thanks for all :)

**Comment by dd4thewin** [comment]
hey is there a trick to get the gpxignorepokemon to work? I got it on true yet its still catching pokemon

**Comment by MadeBySaints** [comment]
@Spegeli You rock. I got the error one more time after starting the new one up, but i let it do its thing, and tis working like a dream - Any links you can share with me, so i can donate to you and Ferox?

**Comment by balput** [comment]
haha it seems like i cant understand how to build it, but thanks anyway guys for explained it to me

**Comment by IstenesImre** [comment]
balput: wait here: https://github.com/NecronomiconCoding/NecroBot/releases

**Comment by dd4thewin** [comment]
keep getting 
[19:22:51] (ERROR) InvalidResponseException from HttpClientExtensions.cs
[19:22:51] Specified argument was out of the range of valid values.
Parameter name: index from Google.Protobuf
[19:22:51] (ERROR) Got an exception, trying automatic restart..
[19:22:51] (INFO) Awesome! You have already got the newest version! 2016.7.28.518
[19:22:51] (ATTENTION) Make sure Lat & Lng is right. Exit Program if not! Lat: 38.5467710604108 Lng: -121.234075080407
[19:22:51] (ATTENTION) Script will continue in 15 seconds!
[19:22:56] (ATTENTION) Script will continue in 10 seconds!
[19:23:01] (ATTENTION) Script will continue in 5 seconds!
[19:23:06] (INFO) Logging in via: Ptc
[19:23:07] Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown. from Pokemon Go Rocket API
[19:23:07] (ERROR) Got an exception, trying automatic restart..

**Comment by KnightMirko** [comment]
Thank you so much! Works like charm. Love you!

**Comment by dd4thewin** [comment]
@Spegeli how do I get gpxingorepokemon to work? its still catching them with that turned true

**Comment by balput** [comment]
@IstenesImre still dont know how to use it, can only understand in @Spegeli version haha

**Comment by balput** [comment]
@Mrbeyond13 i dont know why i always get an error msg when open it in visual studio

**Comment by lacimester** [comment]
@balput https://github.com/NecronomiconCoding/NecroBot/releases
new version without any visual studio :~)

**Comment by Damon200** [comment]
@Mrbeyond13 

I need these long/latitude's 40.781019 -73.781019

how can i put that in console.usersettings.cs ?

**Comment by hadipato** [comment]
hi, iam noobie from asia..
where can i find "Open Pokemon Go Rocket API.sln" ?

**Comment by balput** [comment]
@lacimester but how to configure my location and all that pokemon things ?

**Comment by hadipato** [comment]
i already download https://github.com/NecronomiconCoding/NecroBot/releases
but how to use that? help and guide me please...

**Comment by lacimester** [comment]
@balput just at the config folder at config / auth (config the location + stuffs, and at auth the google/ptc + account information, just right at the previous one)

**Comment by ghosted2014** [comment]
ok that verson just crashes on me when i launch it any idears why ?

**Comment by lacimester** [comment]
but thats doesnt really matter, i just downloaded the latest and still crashes :|

**Comment by Zaackary** [comment]
Same
They just crash on me with this message "(ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown."

**Comment by Zaackary** [comment]
I think the Google Login is just to laggy! http://www.mmoserverstatus.com/pokemon_go

**Comment by ghosted2014** [comment]
yeah load the program then it program not responding and closes lol

**Comment by lacimester** [comment]
@Zaackary , dont think so, i just tested with my Ptc acc and doing the same

**Comment by Zaackary** [comment]
Okay well maybe its over lmao no more hacking we are all gonna have to get our lazy asses outside! :(

**Comment by ghosted2014** [comment]
hahah lol

**Comment by balput** [comment]
seems like i only understand when using @Spegeli version, but thank you anyway @lacimester @Mrbeyond13 for your help, hopefully i can find spegeli version

**Comment by lacimester** [comment]
@Zaackary as i see under the relased version the commits, they are workin on a new soon :P

**Comment by Zaackary** [comment]
Wonderful Hopefully by tonight this will be fixed and working!

**Comment by ghosted2014** [comment]
any idear on how long till its pushed ?

**Comment by Zaackary** [comment]
Yea

**Comment by lacimester** [comment]
there are we, 3.0.1 is on

**Comment by ghosted2014** [comment]
thanks ile post back

**Comment by Zaackary** [comment]
Whats 3.0.1?

**Comment by ghosted2014** [comment]
do you have the link

**Comment by Damon200** [comment]
New link for just .exe ?

**Comment by lacimester** [comment]
https://github.com/NecronomiconCoding/NecroBot/releases

follow this guys, the _just download and start version_ is usually there as i see (but thats spamming me something like pokemon go servers are busy, chill)
