### ISSUE TITLE
Request: Transfer select Pokemon regardless of CP

### ISSUE THREAD

**Issue by A6uh** [Spegeli/PokemoGoBot-GottaCatchEmAll#161]
Could we add a Always Transfer List? Such that would auto transfer specified pokemon regardless of CP or IV? I seem to be running into a problem in NY where my inventory fills with pinsirs and they just keep getting stronger to and being kept even when increasing the keep above CP.

**Comment by XiCynx** [comment]
I think this could be a viable thing to implement, it would basically work exactly opposite of how the Do Not Transfer List works right now.  We'll see what Spegeli thinks!

**Comment by executor819** [comment]
u can do it, just change config

**Comment by Spegeli** [comment]
With pinsirs there is currently a issue. maybe a proto is wrong.
