### ISSUE TITLE
about google login

### ISSUE THREAD

**Issue by jkhunalaguna89** [Spegeli/PokemoGoBot-GottaCatchEmAll#162]
i have check my scurity google and i didnt active my 2 verifikasi but why i have bad aunthetication so i cant use it. any have sugestion sory for my bad english 
![untitled](https://cloud.githubusercontent.com/assets/20712665/17230984/83f2e34c-5549-11e6-8738-ee3b8c9d740e.png)

**Comment by Crankers** [comment]
no CAPS in email?

**Comment by A6uh** [comment]
go to user settings and at the bottom of the page is Google Username and Google Password. You're most likely typing in PTC Username and PTC Password

**Comment by jkhunalaguna89** [comment]
@Crankers no ditz.shop89@gmail.com. 
@A6uh so idont need use @ ?

**Comment by XiCynx** [comment]
No, he's saying make sure that you are putting your credentials in the right spot in the UserSettings.  Here is what he means.  Put your Gmail and Gmail Password at the bottom, not in the PTC Username/Password spot.

https://i.imgur.com/Iqeizhc.png

**Comment by A6uh** [comment]
see [here](https://gyazo.com/843a0f94b07c45ac8eb7b8c8f3f5cb0c) is the wrong spot
[This](https://gyazo.com/770070101e4efc4a830e7d57e98e7352) is where to put your Google login

**Comment by jkhunalaguna89** [comment]
i remove @ from my email and it works. 
i didnt use visual studio.i use notpat ++  i was put my email in google email and dosnt work. i get bad aut.

**Comment by jkhunalaguna89** [comment]
like this and it works ![untitled](https://cloud.githubusercontent.com/assets/20712665/17231814/4e961f34-554e-11e6-9be4-89d8ed3b057e.png)

**Comment by Spegeli** [comment]
WTF this is not my Version?!
Why does people ask here for Support for other Forks/Bots?
