### ISSUE TITLE
evolve every pokemon

### ISSUE THREAD

**Issue by omgwtfisthatthingonyourface** [Spegeli/PokemoGoBot-GottaCatchEmAll#168]
Hi, I am not experienced at all with MVS, but is there a way to evolve every pokemon, or at least some of the common ones like spearow, dodrio, etc? I just want to hit lvl 40 ASAP.

**Comment by AncientGen** [comment]
it evolves as soon as it has enough candies. it wont go looking for that spearow in particular.
But its already doing what you asked *if you didn't turn it off in the app.config

**Comment by Spegeli** [comment]
When EvolvePokemon is enabled, he will Evolve all Pokemons which are inside the PokemonsToEvolve.ini File.
