### ISSUE TITLE
walked miles status

### ISSUE THREAD

**Issue by nabilmoosaje** [Spegeli/PokemoGoBot-GottaCatchEmAll#171]
Can you add how many miles walked live update on top bar?

**Comment by Spegeli** [comment]
the total miles or only from the current session?

**Comment by Spegeli** [comment]
Ok added the Walked Miles for the current Session to the next Version.

**Comment by nabilmoosaje** [comment]
Either will work, just needed to know when to use luck eggs. Thanks

**Comment by ThatGuy2012** [comment]
(NotTransferPokemonsThatCanEvolve)
cont set it to ture why ?
