### ISSUE TITLE
[Minor] Add timeout to web requests // Stuck on 30 Minute Runtime

### ISSUE THREAD

**Issue by kraizy** [Spegeli/PokemoGoBot-GottaCatchEmAll#175]
Hello,
Sometimes web requests will not be finishied due this the bot hangs, to prevent this it would be great if you add a timeout to the web requests so that the requests be killed and the bot can continue (3 of 3 running bots tonight stopped after 1-2 hours due this)

**Comment by Spegeli** [comment]
yeah this comes because we added the following:
````
            while (response.Payload.Count == 0)
            {
                await RandomHelper.RandomDelay(200,300);
                response = await PostProto<TRequest>(client, url, request);
            }
````
because niantic changed the max requests to 2-3 per second.
i will make a 5 time counter and then restart the whole script.

**Comment by Keng073** [comment]
My bot stops at every 30 min. Is there a way for me to fix it?

**Comment by wesyr** [comment]
Keng073 i've vreated an issue with that https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/178

**Comment by Spegeli** [comment]
Maybe i found a solution for this issue but doing now first some local teste before uploading.

**Comment by PeterPlanlos** [comment]
Thank you would be great.

Does we talking here about the error when the bot dont throw an exception and no error, but hang totally and does nothing. Or does we speak abou the excwption which is thrown every half hour and the bot restarts Automatically and does still do the work?

Thanks again.

**Comment by Spegeli** [comment]
With the current version i changed it now to:
````
            var response = await PostProto<TRequest>(client, url, request);
            while (response.Payload.Count == 0 && counter < 5)
            {
                await RandomHelper.RandomDelay(200,300);
                response = await PostProto<TRequest>(client, url, request);
                counter += 1;
                if (response.Payload.Count == 0)
                    Logger.Write("Payload ist 0", LogLevel.Debug);
            }
            if (response.Payload.Count == 0)
            {
                Logger.Write("Payload ist 0", LogLevel.Debug);
                throw new InvalidResponseException();
            }
````
so he should try 5 times to get a new repsonse, otherwise throw the exception
