### ISSUE TITLE
Question: Is there a way to transfer all poke below a certain IV ?

### ISSUE THREAD

**Issue by AsmoAeon** [Spegeli/PokemoGoBot-GottaCatchEmAll#176]

**Comment by Spegeli** [comment]
Enable TransferPokemon.
Set TransferPokemonKeepDuplicateAmount to 0.
Enable UseTransferPokemonKeepAboveIV.
Set IV Value in TransferPokemonKeepAboveIVPercentage.

**Comment by AsmoAeon** [comment]
I tried that. I believe it only works when it encounters/catches that pokemon again. Then it transfers both of them. It does not transfer them the moment i start the bot.

**Comment by Spegeli** [comment]
The bot is doing a Transfer on Startup and then after every pokemon catch.

**Comment by AsmoAeon** [comment]
Mine does not :/ Only when i have 2 of them. 

[] (PKMN) (CatchSuccess) | Spearow - Lvl 13 [CP 196/255 | IV: 14.00% perfect] | Chance: 0.41 | 69.68m dist | with a PokeBall and received XP 210
[] (INFO) Found 2 Pokemon for Transfer:
[] (TRANSFER) Spearow [CP 294/353 | IV: 37.56% perfect] | Best: [CP: 196/255 | IV: 13.88% perfect] | Family Candies: 24
[] (TRANSFER) Spearow [CP 196/255 | IV: 13.88% perfect] | Best: [NONE] | Family Candies: 25

Also please check the first TRANSFER line. 
I have PrioritizeIVOverCP to True and still it sorts them using CP. 
Probably cosmetic "bug". Does not affect anything.

**Comment by kimkimlab** [comment]
dude, the first Spearow IV 37.56% (CP294) then Spearow IV 13.88% (CP196).
37% > 13% and as u said 
> 
> Also please check the first TRANSFER line.
> I have PrioritizeIVOverCP to True and still it sorts them using CP.

you can edit the source to call Transfer function when Walk function called so bot will transfer without catching the pokemon

**Comment by AsmoAeon** [comment]
Nah im mostly debugging the bot. Some days ago it was crashing when you used 0 at TransferPokemonKeepDuplicateAmount. So now that its fixed i was testing that.

**Comment by Spegeli** [comment]
The 0 TransferPokemonKeepDuplicateAmount should be fixed since today.
When i say that something is working and its not working for your, then pls first download the newest version.

**Comment by Denuth** [comment]
It does not transfer the pokemon at startup. Only after it catches one it transfers it if it is a duplicate. Even then it does not transfer away all the other ones. If you need proof let me know.
