### ISSUE TITLE
GPX issue (mscorlib?)

### ISSUE THREAD

**Issue by Avenga9** [Spegeli/PokemoGoBot-GottaCatchEmAll#177]
After starting the bot since yesterday with Use GPX on, the bot continues to spam this after logging in: 

[11:49:08] Die Eingabezeichenfolge hat das falsche Format. from mscorlib
[11:49:08] (ERROR) Got an exception, trying automatic restart..
[11:49:08] (INFO) Logging in via: Google
[11:49:09] (INFO) Client logged in

Without using the GPX feature the bot runs smooth like a cat
I looked around for solutions but couldnt find any, I hope im not wasting someones time now. Thanks for the help! And Spegeli God bless you

Edit: got newest version ofc

**Comment by AsmoAeon** [comment]
Check the instructions about gpx provided here:
https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started
There are some things you need to remove from the gpx file.

**Comment by Avenga9** [comment]
Did that, infact the GPX files i use are provided through this GitHub, using CentralParkPokestops

**Comment by sevarin19** [comment]
are you positive its in the right folder? 

PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI.Console\bin\debug 

is where mine are.

**Comment by Avenga9** [comment]
Yep

**Comment by AsmoAeon** [comment]
"," instead of "." or the opposite ? Though i think its fixed at the last build.

**Comment by Spegeli** [comment]
the GPX fucks a little bit up because of the dot / comma issue depending on the country the user life.

**Comment by Avenga9** [comment]
i tried out both the comma and period versions, both seem to result in the same errors.

Il guess il just wait and hope for further versions to work - bot is also great without gpx

thanks for the anwsers :)

**Comment by AsmoAeon** [comment]
Spegeli maybe you can create a ConvertToDouble function that can guess the culture.
For example you can try to convert "3,14" and see if you get "314" or "3.14".  Something like
If cdbl("3,14") = 314 then ... else ... end if
Kinda dirty method :p

**Comment by XiCynx** [comment]
@Avenga9 Are you able to advise if this is still an issue?

**Comment by Spegeli** [comment]
Should be fixed with latest Version: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/6a691f238dc59b353012573f48bb776b3e1aea11
