### ISSUE TITLE
Bot stops after 30 minutes

### ISSUE THREAD

**Issue by wesyr** [Spegeli/PokemoGoBot-GottaCatchEmAll#178]
After 30 minutes of working, bot stops. 
Just freezes and i need to re-run it.

**Comment by kraizy** [comment]
See #175

**Comment by deryoshi** [comment]
yeah its exactly 30 minutes for me aswell. google and ptc accounts.

**Comment by Keng073** [comment]
Same.

**Comment by PeterPlanlos** [comment]
jup just quit work , no exception no crash just stopped work.

**Comment by sevarin19** [comment]
all 3 of mine have been doing this as well. just downloaded the newest version that looked like it changed a few timing lines. hoping thatll fix it.

**Comment by PeterPlanlos** [comment]
@sevarin19  please report back. thank you

**Comment by Keng073** [comment]
the new update can't build the solution.

**Comment by Keng073** [comment]
the newest update can't even build the solution.

**Comment by sevarin19** [comment]
the version i picked up doesnt seem to have fixed it, but hes in the middle of updating several things by the looks. theres been another update within the last 30 minutes.

**Comment by adrenmedulla** [comment]
How to fix this problem?
