### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Heffyy** [Spegeli/PokemoGoBot-GottaCatchEmAll#179]
![image](https://cloud.githubusercontent.com/assets/20722678/17245404/a066e73e-5586-11e6-8857-6575a4f43216.png)

I got this error since yesterday.
Does anyone know how to fix this?

Thank You.

**Comment by sevarin19** [comment]
installing a newer version fixed that issue for me.

**Comment by Heffyy** [comment]
But even with the newer version it stilldoes that, I tried the older version so see if it would work.
