### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Heffyy** [Spegeli/PokemoGoBot-GottaCatchEmAll#180]
![image](https://cloud.githubusercontent.com/assets/20722678/17245665/c668ebfc-5587-11e6-89c8-e69e7c97eb4b.png)

The newer version did not fix it for me, any other solutions?

Thanks.

**Comment by sevarin19** [comment]
authentication is your login info if im not mistaken. double check. make sure you scroll all the way down in usersettings.settings. new login info is there for google.

**Comment by Heffyy** [comment]
You fixed it.
Thank You.
