### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by Azhy** [Spegeli/PokemoGoBot-GottaCatchEmAll#183]
Basically after yesterdays servers going down, I have had an issue with log in basically what had been happening is that the script will launch as normal but then when It would usually open up a browser page and a code in the script, it just says "Visit & Enter" when the browser opens the script closes.
![960f9f1f53d46422337c38335bf17320](https://cloud.githubusercontent.com/assets/20723849/17247266/faca251c-5589-11e6-8904-ef034e97b3cb.png)

**Comment by AsmoAeon** [comment]
Please check issue #136
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/136

**Comment by Spegeli** [comment]
Upgrade to the latest Version and everything is fine.
I hate it when people report bugs for versions which are already outdated.
