### ISSUE TITLE
PokemonToNotCatch Issue ? 

### ISSUE THREAD

**Issue by TubesForNoobs1** [Spegeli/PokemoGoBot-GottaCatchEmAll#186]
![image](https://cloud.githubusercontent.com/assets/20724149/17247765/2928322a-555b-11e6-9b39-4f77bd893175.png)

![image](https://cloud.githubusercontent.com/assets/20724149/17247776/3fe8297a-555b-11e6-84db-17ce6ca8e2e5.png)

As can be seen by the two images, I have edited the list of pokemon I do not want the bot to go for and ive also turned the value to true in usersettings, However there seems to be no effect at all and the bot catches them regardless. Is there a step that im missing ? or is this an issue for the bot ?

**Comment by Spegeli** [comment]
You have to change them in the PokemonsToNotCatch.ini
The pokemon in the settings are only the default one which be included when the File gets created.

**Comment by TubesForNoobs1** [comment]
thank you, where do I find that folder/file ?

**Comment by TubesForNoobs1** [comment]
nvm, I searched and found it, Thank You very much, Appreciated

**Comment by tahabf** [comment]
You could write where you found it
