### ISSUE TITLE
Pokemon Name's Color & Language

### ISSUE THREAD

**Issue by DreameR321** [Spegeli/PokemoGoBot-GottaCatchEmAll#187]
Heyho,

is it possible to translate the Pokemon name's in German?
There is a list with all Pokemon and there ID - can every one change the Name for themselves?

and i have one idea - on this screen https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/blob/master/Screenshot.png

you see this:
"(POKEBATTLE) We caught a Spearow with CP 406 [...]" is it possible to change the color from "Spearow" so it is easyer to see all pokemon directly.

sorry for my very bad english :/

**Comment by Oolaruu** [comment]
Also would like for French.

**Comment by Spegeli** [comment]
Because we're currently working on a GUI i will not add multi Language Support etc. until the GUI is finished.
