### ISSUE TITLE
[SUGGEST] app.config

### ISSUE THREAD

**Issue by 30er** [Spegeli/PokemoGoBot-GottaCatchEmAll#192]
at the moment we need to modify

PokemonGo.RocketAPI.Console.exe.config

for some settings like username and so on

can u maybe move that into settings folder?

and maybe also add a startup argument for setting the path for setting folder (MULTIUSER)

f.e. you could start the bot like:
bot.exe Settings_ply1
bot.exe Settings_ply2

and it takes than all configs out of settings folder.... would make sense or?

**Comment by Spegeli** [comment]
There will be a GUI soon.
