### ISSUE TITLE
[SUGGEST] Stuck Timer

### ISSUE THREAD

**Issue by 30er** [Spegeli/PokemoGoBot-GottaCatchEmAll#193]
Sometimes my bot stops...
Cant tell you why.
It just writes... 
Distance to target location .... 10 secs

and than nothing for minutes

is it possible to make some Timer that checks for last event... and lets say... after 5 mins without any log/action restart the bot automatically?

**Comment by Spegeli** [comment]
should be fixed with the latest version.
was a issue when he hangs in the repsonse loop.

**Comment by 30er** [comment]
maybe add some kind of "restart" timer anyway
lets say...
20 mins + random of 20 mins
so its kind of "Reconnect" ;)
will look more human ;)
