### ISSUE TITLE
What does that mean ?

### ISSUE THREAD

**Issue by PokeHunter** [Spegeli/PokemoGoBot-GottaCatchEmAll#195]
![gfd](https://cloud.githubusercontent.com/assets/20725041/17249132/bdf8c250-559e-11e6-8512-4c8812577338.PNG)
Yesterday the bot worked fine.. now i'm getting this error

**Comment by Spegeli** [comment]
Wrong Google Login Details in the UserSettings.

**Comment by PokeHunter** [comment]
They aren't wrong.. Ive checked it multiple times
