### ISSUE TITLE
SkiplastFeild

### ISSUE THREAD

**Issue by Alku1** [Spegeli/PokemoGoBot-GottaCatchEmAll#197]
[16:37:04] SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing from Google.Protobuf

i get this whenever i want to login using ptc since the new update

**Comment by Spegeli** [comment]
Go into: PokemonGo.RocketAPI.Console\bin\Debug\Logs
Copy & Past the Log here: http://pastie.org/pastes/new

Remove your Username:
> [15:43:39] PTC Account: JizzMaster2000
> [15:43:39] Your Account:

And then past the Link here.

**Comment by Alku1** [comment]
http://pastie.org/10923070

**Comment by Alku1** [comment]
issue seems to be solved by itself now, i no longer get the error i use to get on hour ago.
 However, do you know what causes this error ?
**[17:41:44] Encounter problem: PokemonInventoryFull**

Here is a log; http://pastie.org/10923073

**Comment by Spegeli** [comment]
It seems your Pokemon Bag is full.
Clean up some space.
