### ISSUE TITLE
How can i fix this ?

### ISSUE THREAD

**Issue by PokeHunter** [Spegeli/PokemoGoBot-GottaCatchEmAll#198]
![gg](https://cloud.githubusercontent.com/assets/20725041/17250457/b726239a-55a4-11e6-918a-fe944a72acc7.PNG)
The cords are correct but there are no pokestops

**Comment by Spegeli** [comment]
When you change the Default Cords via UserSettings you should always remove the LastCoords.ini from the Settings folder.

**Comment by PokeHunter** [comment]
Where is the settings folder ? Sry im not that great in these things

**Comment by Spegeli** [comment]
In your Explorer: PokemonGo.RocketAPI.Console\bin\Debug\Settings

**Comment by PokeHunter** [comment]
Thanks
