### ISSUE TITLE
Add Manual Pokemon Transfer Manually

### ISSUE THREAD

**Issue by xquiaz** [Spegeli/PokemoGoBot-GottaCatchEmAll#199]
i have problem with auto transferred, still have bug where set IV 80% and CP 1500. Pokémon under IV and CP what I set cannot transferred automatically.
thanks

**Comment by Spegeli** [comment]
Please attach a Screenshot of your Settings.

**Comment by xquiaz** [comment]
DefaultAltitude 
 10 
 TransferPokemonKeepAboveIVPercentage 
 80 
 
 TransferPokemonKeepAboveCP 
 1500 
 
 WalkingSpeedInKilometerPerHour 
 100 
 
 DefaultLatitude 
 -33.863289 
 
 DefaultLongitude 
 151.215305 
 
 UsePokemonToNotCatchList 
 False 
 
 AuthType 
 Google 
 
 PtcUsername 
 Username 
 
 PtcPassword 
 Password 
 
 PrioritizeIVOverCP 
 True 
 
 MaxTravelDistanceInMeters 
 1000 
 
 UseGPXPathing 
 False 
 
 GPXFile 
 GPXFILE.gpx 
 
 UseLuckyEggs 
 False 
 
 NotTransferPokemonsThatCanEvolve 
 False 
 
 EvolveOnlyPokemonAboveIV 
 False 
 
 EvolvePokemon 
 False 
 
 EvolveOnlyPokemonAboveIVValue 
 95 
 
 TransferPokemon 
 True 
 
 TransferPokemonKeepDuplicateAmount 
 2 
 
 UseTransferPokemonKeepAboveCP 
 True 
 
 UseTransferPokemonKeepAboveIV 
 True 
 
 UsePokemonToNotTransferList 
 True 
 
 UseIncense 
 False 
 
 GoogleEmail 
 ----
 
 GooglePassword 
 ---- 
 
 GPXIgnorePokemon 
 False 
 
 GPXIgnorePokestops 
 False

**Comment by Spegeli** [comment]
It will keep all with IV > 80 and CP > 1500.
And then he will keep 2 others.
If he should ONLY keep IV and CP, then set TransferPokemonKeepDuplicateAmount  to 0

**Comment by xquiaz** [comment]
i'll try it, thanks man!
