### ISSUE TITLE
[WalkingSpeedInKilometerPerHour] Always Catchflee over 50 KM/H

### ISSUE THREAD

**Issue by branisla** [Spegeli/PokemoGoBot-GottaCatchEmAll#203]
Hello,

I've tried many speed and it is always the same issue : 

When i'm over 50 Km/H, I can catchsuccess one pokemon. After that all pokemon are on state catchflee.

is someone else has the same issue ?

Bran

**Comment by Spegeli** [comment]
This is a Server think which happens randomly.
I use 150 km/h most of the time without any issues.

**Comment by Vlieker** [comment]
Hey,

I have this issue too 50% of the Pokemon flee

**Comment by Napcazz** [comment]
I have same issue too

**Comment by xquiaz** [comment]
use newest version I think, and Anti-Softban working automatically.

**Comment by branisla** [comment]
ok ty for the answers :)

**Comment by branisla** [comment]
and of course many thanks for this great work on the bot !! spegeli

**Comment by Vlieker** [comment]
I have the latest update :P
