### ISSUE TITLE
feature request: bot for macintosh

### ISSUE THREAD

**Issue by ibbatta** [Spegeli/PokemoGoBot-GottaCatchEmAll#205]
Please could you migrate the technology to run the bot on a mac client?

**Comment by Spegeli** [comment]
I don't own a UNIX System so i can't make the compatible, sorry.
But you can maybe use a Virtual Maschine with Windows and let it run there.

**Comment by ibbatta** [comment]
I could use a vm, but then i need to install Visual Studio, etc... don't you think is more useful provide a compiled version of this? It would be a great service to noob win user like me.
