### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by Vlieker** [Spegeli/PokemoGoBot-GottaCatchEmAll#206]
Hello,

When I want to play I have no revives/potions, is there an option that the bot doesn't recycle almost everything I have?

**Comment by xcr89** [comment]
edit settings.cs file before building

**Comment by Vlieker** [comment]
Ty

**Comment by 30er** [comment]
u can change it directly in code

PokemonGo.RocketAPI.Console/Settings.cs

**Comment by Hydraks** [comment]
How to disable recycle ? there is a bool to activate or not recycle ? 
Thanks

**Comment by Spegeli** [comment]
No Toggle yet. simply set all to 1000 in the Settings.cs
but then you maybe run out of pokeballs or get other issues.
