### ISSUE TITLE
[QUESTION] Sometimes my bot keeps saying "No pokestops found nearby..."

### ISSUE THREAD

**Issue by glenn1200** [Spegeli/PokemoGoBot-GottaCatchEmAll#207]
hey, first of all, really nice bot! I enjoy it very much.

I have a problem though, sometimes after a while it keeps saying that there are no pokestops nearby and that my distance might be too low. Even when i have distance set to 10km(10000 in the settings as it is in meters)

Any fix? I live in a place with quite a lot of stops.

**Comment by Spegeli** [comment]
This is a random Server issue like the CatchFlee etc.
Try another Location or wait some Minutes, then it should work again.

**Comment by glenn1200** [comment]
have waited for 5mins but still stops working. other bots on same location have been going for 40min+

**Comment by glenn1200** [comment]
nvm started working, thanks!
