### ISSUE TITLE
[REQUEST] Hitting PokeStops is customizeable

### ISSUE THREAD

**Issue by Linewalker** [Spegeli/PokemoGoBot-GottaCatchEmAll#218]
For not gaining too much XP, I implemented an user option "Hit Pokestops" (True/False) and added this option to ExecuteFarmingPokestopsAndPokemons (stating at "do" ... to "while"). Now the client walks around, catching Pokemons without getting XP at Pokestops. Perhaps is this a option for all.
![screenshot_74](https://cloud.githubusercontent.com/assets/7597479/17270426/8e66fc68-5662-11e6-88b6-e44d772af886.png)

**Comment by Spegeli** [comment]
And why should we ignore the Pokestops XP?

**Comment by Linewalker** [comment]
Idk, let the user decide if he/she wants it or not :-)

**Comment by Trinic07** [comment]
@Linewalker How can i enable that? In Usersettings "GPXIgnorePokestops true do not work.

**Comment by Linewalker** [comment]
You can't enable it. As I already mentioned, I changed the bot myself and made this option as a suggestion.

**Comment by XiCynx** [comment]
There is already this option for GPXRoutes, are you wanting this implented for free roam mode them as well?

**Comment by Linewalker** [comment]
This option doesn't take care of GPX or normal mode. Off means off ;)

**Comment by Trinic07** [comment]
@Linewalker can you maybe upload the files, you have changed? or show me the code

**Comment by Linewalker** [comment]
Have a look at the request. There's also a do ... while loop in the task above. This has also to be changed.
