### ISSUE TITLE
Auto hatch egg using Unlimited Egg Incubator

### ISSUE THREAD

**Issue by Crizpy** [Spegeli/PokemoGoBot-GottaCatchEmAll#22]
First of all Probs to you and Ferox ,
the bot in its current state run fully automatic and you dont need to do anything like removing items or stuff.
Just 2 more missing Stuff is really important : 
The Automatic Lucky Egg - As i want to level asap to lvl 40 Lucky Eggs are key , but i cant log in every 30 minutes so please add this feature .
Automatic Egg Hatching - Would be awesome .

**Comment by Spegeli** [comment]
Its on ToDo list but currently no ETA

**Comment by Spegeli** [comment]
Added with the latest Version: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/806009cb6d4da6183b12235e7caa9cc2e28b68b3
