### ISSUE TITLE
Instead of 10 best IV/CP, the whole complete list of pokemon owned with IV/CP by command input~~

### ISSUE THREAD

**Issue by rokuon** [Spegeli/PokemoGoBot-GottaCatchEmAll#221]
so that anytime we can check list of our pokemon name a-z or number based with complete IV/CP details just with inputting command..

**Comment by Spegeli** [comment]
Please post your request in this ticket: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/11

**Comment by rokuon** [comment]
okok sir
