### ISSUE TITLE
InvalidResponseException

### ISSUE THREAD

**Issue by Skovisen** [Spegeli/PokemoGoBot-GottaCatchEmAll#222]
Hi. Love your bot. Even so, seems like PokemonGo.RocketAPI.Exceptions.InvalidResponseExceptions is back at it again.

**Comment by Spegeli** [comment]
Which Bot version do you use? You can find this info in the log file (first few lines).

**Comment by Skovisen** [comment]
2016.7.30.588, which I believe is the latest, if I'm not entirely wrong.

**Comment by Skovisen** [comment]
Hmm, don't know what that was, but it seems it fixed itself. No longer have the problem, I'll close.
