### ISSUE TITLE
Cannot find any usable PokeStops in your area.

### ISSUE THREAD

**Issue by Killmachine** [Spegeli/PokemoGoBot-GottaCatchEmAll#223]
Just downloaded the newest version. The old one was working fine. Now I get the message "Cannot find any usable PokeStops" even though I am using the coords I have been using for the last five days and they were working perfectly (central park coords). My max distance in meters is 1500. What is wrong?

**Comment by Killmachine** [comment]
Now I got the message "You are outside of your defined radius". Somehow my bot got so far away from my original coords (am I right?) and causing this. Now he is walking back to the coords, what should I do to not recieve these messages?

**Comment by linsvatten** [comment]
It´s the same for me

**Comment by fexacana** [comment]
its started me when i changed the coords. i though anti-softban is working. actually, sometimes bot works appr 5-10 mins but then same message.

**Comment by Killmachine** [comment]
Good to know I am not the only one experiencing this issue.

**Comment by Logilac** [comment]
I have the same issue too. I read that the problem is server side and that it has nothing to do with the server but the server are online and working fine.

**Comment by XiCynx** [comment]
this issue tends to happen more in more populated areas. If you go to somewhere that is not as populated, AKA outside of Central Park, Santa Monica, etc, you should not run into this issue as much as you are now.

**Comment by fexacana** [comment]
i am farming santa monica and not encounter this issue but try to farm in central park its happened.
