### ISSUE TITLE
[REQUEST] WP/IV/Level Maximum

### ISSUE THREAD

**Issue by Ult1mo** [Spegeli/PokemoGoBot-GottaCatchEmAll#227]
Hello!
First of all I would like to thank you for your great work :)
Well I think I have a good improvement for the bot...

As at the moment it is only possible to define a IV Percentage to keep the Pokemon and CP to keep a Pokemon.
It would be awesome to have an option to keep a IV-Percantage Pokemon with a specified Pokemon-Level and Above.
As an example I would use a 90% IV-Value and Pokemon-Level 20. Then it would only keep Pokemon that are 90% perfect and have a minimum Level of 20. 
So I can minimize the Stardust-Value needed and maximize the IV-Value at the same time.

Thank you for your time reading this.
Regards

**Comment by Kongolan** [comment]
Already got this:
            ```
if (_client.Settings.UseTransferPokemonKeepAboveIV)
            {
                // remove pokemon with too low CP even with good IV
                pokemonList = pokemonList.Where(p => (PokemonInfo.CalculatePokemonPerfection(p) < _client.Settings.TransferPokemonKeepAboveIVPercentage) || (p.Cp < 380)).ToList();
            }
```
Basically it does only keep good IV if they have above 380 CP, because rest is just trash.

**Comment by XiCynx** [comment]
Not the same thing as what is in there now. I understand what he means, its something I was going to write up a bit better in a day or so. Going to close this and submit a more detailed version of this tomorrow. :)
