### ISSUE TITLE
[Request] Pokemon Movesets

### ISSUE THREAD

**Issue by Lexblack** [Spegeli/PokemoGoBot-GottaCatchEmAll#228]
Is it possible to include the movesets of each pokemon in the export file?

**Comment by Spegeli** [comment]
What do you mean mit MoveSets?
The Attack Names are already in the Export File.

**Comment by Jadonas** [comment]
@Spegeli Can you add an option to transfer bad moveset pokemons [cant evolved pokemons]

**Comment by ellm62** [comment]
KeepOnlyGoodMovesets setting would be great. E.g. if a psychic pokemon ends up with Confusion instead of Psycho Cut then it's useless. 

I have a CSV file with every pokemons best moveset - I can provide you with a copy if you decide to implement this feature.

**Comment by Jadonas** [comment]
@ellm62 can u upload it ?

**Comment by ellm62** [comment]
@Jadonas Sure: https://drive.google.com/open?id=0BzmQWRiYC2FzMUhQWVd4d1lTbDQ
Let me know if you incorporate it :P

**Comment by Spegeli** [comment]
Currently i will not implant such a function, sorry.
