### ISSUE TITLE
is there anyway to login to anybot by using 2 factor authentication? or through the refresh token

### ISSUE THREAD

**Issue by YamattoK** [Spegeli/PokemoGoBot-GottaCatchEmAll#232]
Guys..... My gmail account is issued by our organization, so I cannot turn off the 2 factor authentication nor get a app key... is there anyway to login to anybot by using 2 factor authentication? or through the refresh token which I stored previously?

**Comment by XiCynx** [comment]
There is not. Use Ptc instead.
