### ISSUE TITLE
[REQUEST] Auto-gym retake

### ISSUE THREAD

**Issue by Arthurhoeke** [Spegeli/PokemoGoBot-GottaCatchEmAll#233]
Would it be possible to add an automatic gym retake system / pokemon adder if the gym is the same team as the trainer?

**Comment by snapo** [comment]
i dont think that is a good idea... because until now it does not hurt other players... if this would be implemented, then the bots win... and then niantic takes immediate actions

**Comment by Spegeli** [comment]
I will not implant any Gym Features, this will break the Game completely.
