### ISSUE TITLE
[Request]Delay between catch

### ISSUE THREAD

**Issue by Nocteus** [Spegeli/PokemoGoBot-GottaCatchEmAll#237]
Hello guys,  first congrats on your bot, this is the best one actually.

I just miss one features that allows to set a delay between pokemon catches in order to be more stealthy (because when we encounter 3 pokemons the bot captures them all in 3 secondes ^^) i think this is a bit suspicious.

I saw this feature in Haxton's bot if i remember correctly.

And just an idea, don't know if it's doable (i guess yes, the bot counts the distance between the pokestops) but it could be cool to add a distance counter

 thank you guys !

**Comment by BudiZhu** [comment]
I agree with this suggestion. To be more realistic between catch. I modified mine to have this feature.

**Comment by Spegeli** [comment]
Delays and Huminzer things will not prevent us from (permanent) Banns (when they come).
