### ISSUE TITLE
Catchflee

### ISSUE THREAD

**Issue by marzmarz** [Spegeli/PokemoGoBot-GottaCatchEmAll#239]
Hi, thanks for making this great bot.
I want to ask why when I am botting the catchflee is very often, so I did not catch many pokemon.
I mainly got exp from pokestop only.
Until I reach level 20++, I only catch around 300 pokemon.
Do you have any suggestion about this?
Thanks

**Comment by BudiZhu** [comment]
I did encountered this problem too. The only solution that I try is lower the walking speed to 50. The bot can detect the softban in pokestop but it can't bypass the catch flee because moving too fast. This issue occured if the pokestops in your area are close each other.
