### ISSUE TITLE
PTC login issue

### ISSUE THREAD

**Issue by superpitzi2** [Spegeli/PokemoGoBot-GottaCatchEmAll#240]
[04:31:55] Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown. from Pokemon Go Rocket API

When I try to login via PTC it wont work, it worked before I updated, now it wont work with old version or new.

Login is working to site, but not to the bot.

thanks

**Comment by BudiZhu** [comment]
Actually, it's so ironic. My bot can login and botting but my Pokemon Go app in my phone could not login me to the server.

**Comment by superpitzi2** [comment]
I know you closed this, but I still get the same error, I can log in via PTC site, but can not login with the bot, at least would you tell me whats wrong? I will try to make another account to see if the account is the problem, but I am sure is not.

thank you and good job for your work
