### ISSUE TITLE
seems to ignore most pokestops when using gpx

### ISSUE THREAD

**Issue by sevarin19** [Spegeli/PokemoGoBot-GottaCatchEmAll#245]
a few days ago running my gpx, it hit pokestops constantly, but lately all it does is travel.

this was a self made gpx that only had pokestop destinations. ive tried multiple ones, including some of the premades over at necrobot. 

it gets to its destination, then continues on. im moving at 15kph, so that shouldnt be causing it. it catches pokemon, but rarely, if ever, uses a pokestop.

running my gpx with the newest version for the last 9 minutes, and it hasnt used a single pokestop

GPXIgnorePokestops is set to false

i should mention that the pokestops havent been collected in well over 20 minutes, so its not an issue of them not being up.

not using gpx, but keeping my location as the beginning of my route collects several pokestops immediately.

**Comment by Spegeli** [comment]
It ignore no Pokestops, he only use them when in 40 yard Range.
