### ISSUE TITLE
How Get Pokemon Location?

### ISSUE THREAD

**Issue by mearymary** [Spegeli/PokemoGoBot-GottaCatchEmAll#246]
I'd like to know the location of the Pokemons near itself and acquisition method of latitude. 
Information on acquired POKESTOPS showed that I'm looping and am checking Encount of Pokemons each time. Thank you.

**Comment by Spegeli** [comment]
So you want the Pokemon Latitude and Longitude Cords when doing a Battle?

**Comment by mearymary** [comment]
Not do a Battle.  I want to make 「Pokemon Latitude and Longitude」 list

**Comment by Spegeli** [comment]
Sorry currently its not planned.

**Comment by mearymary** [comment]
Thank you very much for your answer!
