### ISSUE TITLE
skiplastfield called on an end-group tag error.

### ISSUE THREAD

**Issue by maximoney1994** [Spegeli/PokemoGoBot-GottaCatchEmAll#250]
can't seem to get the bot running quite well ever since the last update I get prompted with this message.
![37bdc9ca34df4826af982685a497588b](https://cloud.githubusercontent.com/assets/17068496/17278437/a2a14750-575d-11e6-8714-805fd6894406.png)

**Comment by Spegeli** [comment]
PTC Servers are currently unstable.

**Comment by maximoney1994** [comment]
ur right, google seems to work fine. my bad :/
