### ISSUE TITLE
Process can't access LastCoords.ini because it's already used by another process

### ISSUE THREAD

**Issue by Nestade** [Spegeli/PokemoGoBot-GottaCatchEmAll#251]
Hello,

I'm getting the following error in the console after a few minutes:
Der Prozess kann nicht auf die Datei "C:\Windows\system32\Settings\LastCoords.ini" zugreifen, da sie von einem anderen Prozess verwendet wird. from mscorlib

Translated it means something like "The procces can't access the file "C:\Windows\system32\Settings\LastCoords.ini" because it is already used by another process (by mscorlib)".

What did I do wrong?

Regards,
Nestade

**Comment by PeterPlanlos** [comment]
seems your working dir is your system32 folder? why?
sieht aus als wäre dein arbeitsordner der system32 ordner? warum?

**Comment by Nestade** [comment]
Hi,

Das kam mir auch komisch vor - eigentlich ist es auf D:\PokemonGO und da sind dann die einzelnen Bots drinnen

**Comment by PeterPlanlos** [comment]
findest du die datei?
C:\Windows\system32\Settings\LastCoords.ini

**Comment by Nestade** [comment]
Nein, die existiert gar nicht^^

**Comment by PeterPlanlos** [comment]
bin im moment nicht auf dem aktuellem commit ich bin auf dem 230er noch.
welches verwendest du?

**Comment by Nestade** [comment]
Ich bin auf dem aktuellsten - denke aber, dass der Fehler nur bei mir besteht, sonst hätte den schon wer gemeldet.

**Comment by PeterPlanlos** [comment]
hm verwendest du ihn auf dem rechner wo du ihn kompiliert hast?
falls nich check mal die .net framework version

**Comment by Nestade** [comment]
Scheint beim Compilen einen Fehler gegeben zu haben - jetzt scheint alles zu funktionieren :)
Danke dir nochmal
