### ISSUE TITLE
Error, trying automatic restart..

### ISSUE THREAD

**Issue by PokemonGogogo** [Spegeli/PokemoGoBot-GottaCatchEmAll#252]
Hi, I downloaded the newest version today and tried. Then I found it seems I had issue with authenticating my google account. I tried to delete GoogleAuth.ini but there was no folder called Configs under the folder of Debug. Do you have any idea that what I should do? I'll appreciate it if you can help.

BTW, my google account is authorized by Google to my college. It is @lionmail.com. Does that Matters?

Thanks again.

**Comment by Spegeli** [comment]
Set eMail & Password via UserSettings, then everything is working.
2 Step Authentication is currently not supported.

**Comment by PokemonGogogo** [comment]
Thank you! It works.
