### ISSUE TITLE
[Request] Telegram Bot

### ISSUE THREAD

**Issue by Nestade** [Spegeli/PokemoGoBot-GottaCatchEmAll#253]
Hello,

Could you add a telegram bot like this one?
https://github.com/Ar1i/PokemonGo-Bot

I think your bot has been used as source for the other one.
Would be really nice :)

Regards,
Nestade

**Comment by executor819** [comment]
really nice bot,,, gui so awesome

**Comment by includes08** [comment]
Honestly, i wouldn't waste time in integrating telegram, imo its a useless option to have.

**Comment by rokuon** [comment]
pity Ar1i's doesnt have IV priority
