### ISSUE TITLE
upon start up, no usable pokestops in your area, is the area too small?

### ISSUE THREAD

**Issue by lotsobearfreshtea** [Spegeli/PokemoGoBot-GottaCatchEmAll#254]
exactly same settings. 1 bot works, the other bot does'nt work.

2000 meter radius @ central park,

any ideas?

also after around 15 mins / only visits pokestops, and does not catch any pokemon. 

please help?

**Comment by 30er** [comment]
as discussed the last time
central park is a bit buggy...
try some other place ;)

LA
San Diego
Tokyo

be creative ;)

**Comment by lotsobearfreshtea** [comment]
mate, thanks for the reply. 

appreciate it.
