### ISSUE TITLE
[Request] Pokestop Coordinates

### ISSUE THREAD

**Issue by AsmoAeon** [Spegeli/PokemoGoBot-GottaCatchEmAll#255]
Is it easy to add the pokestop's coordinates after its name ?
For example:
(POKESTOP) Name: XXX in 67.94 m distance (lon=xx.xxxxxx lat=yy.yyyyyy)

This will make it easy to create a GPX file containing only the pokestops the user wants.

**Comment by Spegeli** [comment]
With the next Version you get the following additional output, when Debug Mode is "True":

> [00:44:08] (POKESTOP) Name: New Amsterdam Theatre in 48,83 m distance
> [00:44:08] (DEBUG) Latitude: 40,756241 - Longitude: -73,987527

**Comment by AsmoAeon** [comment]
Awww thank you man :)

**Comment by Spegeli** [comment]
But it will look this way:

> 00:50:12] (POKESTOP) Name: The Lambs Club in 59,08 m distance  | Latitude: 40,756555 - Longitude: -73,984523

**Comment by Spegeli** [comment]
Version is up. Have fun.
