### ISSUE TITLE
Fastest bot ever !

### ISSUE THREAD

**Issue by mfron** [Spegeli/PokemoGoBot-GottaCatchEmAll#256]
![sans titre](https://cloud.githubusercontent.com/assets/11887274/17279299/eddc897e-5770-11e6-9f76-cbef201cd06f.png)

https://github.com/mfron/Pokemon-Go-Bot

**Comment by kraizy** [comment]
go away with ur shit

**Comment by Tempritscher** [comment]
Bot sucks
