### ISSUE TITLE
Broken ? NotTransferPokemonsThatCanEvolve cont set it to ture why ?

### ISSUE THREAD

**Issue by ThatGuy2012** [Spegeli/PokemoGoBot-GottaCatchEmAll#257]
(NotTransferPokemonsThatCanEvolve)
cont set it to ture why ?
is default is false but you cont change to ture.
say something like bool.

**Comment by Spegeli** [comment]
Because its   "True" and not "Ture"

**Comment by ThatGuy2012** [comment]
oh i feel dumb sorry keep up the good work
