### ISSUE TITLE
Got Protobuf.InvalidProtocolBufferException

### ISSUE THREAD

**Issue by benwuhua** [Spegeli/PokemoGoBot-GottaCatchEmAll#258]
[00:28:51] SkipLastField called on an end-group tag, indicating that
onding start-group was missing from Google.Protobuf

**Comment by maximoney1994** [comment]
same problem here 
![cc3bad4aa1e4417080562753d53d73bc](https://cloud.githubusercontent.com/assets/17068496/17281116/bec2ed08-5799-11e6-81e6-65b642a84f47.png)

**Comment by maximoney1994** [comment]
tried both google auth or ptc auth. same result ran on a vps with german ip.

**Comment by benwuhua** [comment]
I also run it on amazon's vps !

**Comment by maximoney1994** [comment]
weird where is ur vps stated germany aswel?

**Comment by benwuhua** [comment]
see this discuss:

**Comment by benwuhua** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/1

**Comment by benwuhua** [comment]
Encamy commented 6 hours ago
I found solution!
I update firmwre at wifi router to dd-wrt
Then I have set up VPN
After that I create VPN connection at instance (amazon aws)
The next step - to run the bot
Bot works excellent!
P.S. sorry for my english. Hope it will be usefull

**Comment by maximoney1994** [comment]
yes but doesnt running a vpn on ur vps disconect you? you have skype so we can talk easier?

**Comment by benwuhua** [comment]
sorry , I'm at work , my boss banned Skype. How do you connect your vps ? windows RDP？vpn won't disconect  you

**Comment by maximoney1994** [comment]
yes I use windows rdp. you sure? doesnt the ip you connect to changes while you go on the vpn?.

**Comment by benwuhua** [comment]
vpn just change your vps out message ip , the vpn server transfer the message betwwn your vps and the remote end,  The In message from your rdp end doesn't change

**Comment by maximoney1994** [comment]
what vpn do you use? can't get it to work. everytime the vpn on the vps connects it drops the rdp connection. only thing I can do is reboot the vps to fix it.

**Comment by Spegeli** [comment]
Made now a better Exception Output:
````
                catch (InvalidProtocolBufferException ex) when (ex.Message.Contains("SkipLastField"))
                {
                    Logger.Write("Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..", LogLevel.Error);
                    await Task.Delay(5000);
                    Environment.Exit(0);
                }
````

**Comment by ryanskidmore** [comment]
+1 Was running the bot on an Azure VM (EU) and i'm getting the same issue.

Could they have possibly banned all non-residential ISPs?
