### ISSUE TITLE
pokemon skills

### ISSUE THREAD

**Issue by Napcazz** [Spegeli/PokemoGoBot-GottaCatchEmAll#262]
can you add pokemon skills settings.

ex:
Ivysaur	Vine Whip	Power Whip
Venusaur	Vine Whip	Sludge Bomb
Charmander	Scratch	Flamethrower

Otherwise transfer pokemon.

**Comment by Spegeli** [comment]
Currently not, to complexe. 
Maybe when the GUI Version is released.
