### ISSUE TITLE
Evolve Problem

### ISSUE THREAD

**Issue by acgame123** [Spegeli/PokemoGoBot-GottaCatchEmAll#265]
I have add the pokemonId in the evolve list, but it just evolve zubat pidgey rattata.
It do not work with other pokemon that I added.
Please help to check the list below.Thank you.

public ICollection<PokemonId> PokemonsToEvolve
        {
            get
            {
                //Type of pokemons to evolve
                var defaultPokemon = new List<PokemonId> {
                    PokemonId.Zubat, PokemonId.Pidgey, PokemonId.Rattata, PokemonId.Caterpie, PokemonId.Weedle, PokemonId.Spearow, PokemonId.Ekans, PokemonId.Pikachu, PokemonId.Sandshrew, PokemonId.Clefairy, PokemonId.Vulpix, PokemonId.Jigglypuff, PokemonId.Oddish, PokemonId.Paras, PokemonId.Venonat, PokemonId.Diglett, PokemonId.Meowth, PokemonId.Psyduck, PokemonId.Mankey, PokemonId.Growlithe, PokemonId.Poliwag, PokemonId.Bellsprout, PokemonId.Tentacool, PokemonId.Ponyta, PokemonId.Slowpoke, PokemonId.Magnemite, PokemonId.Doduo, PokemonId.Seel, PokemonId.Grimer, PokemonId.Shellder, PokemonId.Drowzee, PokemonId.Krabby, PokemonId.Voltorb, PokemonId.Exeggcute, PokemonId.Cubone, PokemonId.Koffing, PokemonId.Rhyhorn, PokemonId.Horsea, PokemonId.Goldeen, PokemonId.Staryu, PokemonId.Omanyte, PokemonId.Kabuto
                };
                _pokemonsToEvolve = _pokemonsToEvolve ?? LoadPokemonList("PokemonsToEvolve.ini", defaultPokemon);
                return _pokemonsToEvolve;
            }

**Comment by Icer2000** [comment]
You need to change the settings in the pokemonstoevlolve.ini in the settings directory.

**Comment by acgame123** [comment]
Excuse me, I can only found this in setting. I tried to restart few times.
![image](https://cloud.githubusercontent.com/assets/20767735/17287651/7bfc8636-5803-11e6-9ef8-06cb5ed7049d.png)

**Comment by Bakeneko** [comment]
You need to either erase your PokemonGo.RocketAPI.Console\bin\Debug folder and recompile or edit the PokemonGo.RocketAPI.Console\bin\Debug\Settings\PokemonsToEvolve.ini file

**Comment by acgame123** [comment]
@Bakeneko It‘s work. Thank you very much

**Comment by OhhPian** [comment]
@Bakeneko Do you mean i need to add the pokemon name in the PokemonsToEvolve.ini file ? And then just compile it ?

**Comment by Bakeneko** [comment]
@OhhPian Just edit the file and run the bot.

**Comment by OhhPian** [comment]
@Bakeneko is this works with all pokemons ? or just for first level pokemon?
