### ISSUE TITLE
I don't know how to use this

### ISSUE THREAD

**Issue by kkaito34** [Spegeli/PokemoGoBot-GottaCatchEmAll#266]
since there's no .exe file,i don't know what to do
i know that user settings can be via notepad though
thanks for your help

**Comment by ibbatta** [comment]
You have to install Microsoft Visual Studio (2005 i think) and run from there

**Comment by Punjay** [comment]
download and install:
https://www.visualstudio.com/de-de/downloads/download-visual-studio-vs.aspx

open: Pokemon Go Rocket API.sln
edit in config ur login auth : google or ptc    id and pw....
set ur coordinates in app.conf
start debug

**Comment by ibbatta** [comment]
@Punjay where i can find "config" ?

**Comment by kkaito34** [comment]
thank you so much!!
