### ISSUE TITLE
ItemRecycleFilter Option.

### ISSUE THREAD

**Issue by Punjay** [Spegeli/PokemoGoBot-GottaCatchEmAll#267]
Hi
I have a bag for 800items, if i stop the bot, and walk outside. I getting a problem with my pokeballs and all other items. Can you build in a custom option for the bag sizes?

so i can change fast at config my sitze of bag: 
 
350items=PokeBall 25, GreatBall 50, UltraBall 75, SuperPotion 10, HyperPotion 25, MaxRevive 25...
400items=PokeBall 25, GreatBall 75, UltraBall 100, SuperPotion 10, HyperPotion 25, MaxRevive 25...
450items=PokeBall 25, GreatBall 75, UltraBall 100, SuperPotion 35, HyperPotion 50, MaxRevive 25...
500items=PokeBall 25, GreatBall 100, UltraBall 100, SuperPotion 35, HyperPotion 50, MaxRevive 50...
...
1000items=PokeBall 25, GreatBall 150, UltraBall 250, SuperPotion 160, HyperPotion 175, MaxRevive 100...

**Comment by Spegeli** [comment]
Why do you get a Problem? Simply change the Values in the Settings.cs to what you want?!
