### ISSUE TITLE
[REQUEST] Proxy Support

### ISSUE THREAD

**Issue by BuschMartin** [Spegeli/PokemoGoBot-GottaCatchEmAll#268]
Proxy Support would be nice.

I could add it if you like....

**Comment by Spegeli** [comment]
You can make a PR, then i will take a look.

**Comment by MythHack** [comment]
use shadowsocks it works

**Comment by BuschMartin** [comment]
@MythHack a socks proxy is no real solution. Normally there is only a http/https proxy available and I don't see why I should use a socks proxy if there are only http requests?

**Comment by LesterLyu** [comment]
Http proxy is already supported, add the following to the console config file.

<system.net>
  <defaultProxy>
    <proxy
      proxyaddress="http://[your proxy address and port number]"
      bypassonlocal="false"
    />
  </defaultProxy>
</system.net>

**Comment by MythHack** [comment]
@BuschMartin shadowsocks is a software. It can solve your problems through global proxy. Of course, you can also choose to use pac file

**Comment by BuschMartin** [comment]
I think @LesterLyu solution would do it. thanks!
