### ISSUE TITLE
Version unsupported by vss 2015

### ISSUE THREAD

**Issue by fishredleung** [Spegeli/PokemoGoBot-GottaCatchEmAll#269]
When I tried to open rocket api with Microsoft visual studio 2015 ,
These messages appeared

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - PokemonGo.RocketAPI, "C:\Users\red\Downloads\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj"
	 - PokemonGo.RocketAPI.Console, "C:\Users\red\Downloads\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI.Console\PokemonGo.RocketAPI.Console.csproj"
	 - PokemonGo.RocketAPI.Logic, "C:\Users\red\Downloads\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI.Logic\PokemonGo.RocketAPI.Logic.csproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Pokemon Go Rocket API, "C:\Users\red\Downloads\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\Pokemon Go Rocket API.sln"

**Comment by Punjay** [comment]
Hi iam using
Microsoft Visual Studio Enterprise 2015 update 3
and it works perfectly ....

**Comment by Spegeli** [comment]
I think we all use mostly VS 2015 (including myself).
You say:
> When I tried to open rocket api with Microsoft visual studio 2015 ,
> These messages appeared

And the Message self includes this:
> These projects can be opened in **Visual Studio 2015**, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.

**Comment by fishredleung** [comment]
Tried doing anything , still can't open it

**Comment by fishredleung** [comment]
Maybe because I m using virtual machine in Mac OS, 
Is it possible that I can run this application in Mac OS ?

**Comment by Spegeli** [comment]
Thats maybe possible.
I never used a Unix System so i cant help you in this case, sorry.

**Comment by Kimmax** [comment]
Mono can run the bot on my linux server without problems, however I had to hack the SSL connections to work with mono, because their SSL implementation is basically ****, so you should be able to run a compiled binary on osx with mono too.
You may be able to compile on osx too, but I didn't try that
