### ISSUE TITLE
Error - InvalidResponseException

### ISSUE THREAD

**Issue by ShooterOS** [Spegeli/PokemoGoBot-GottaCatchEmAll#270]
"PokemonGo.RocketAPI.Exceptions.InvalidResponseException'" Does anyone know why this happened?

**Comment by Spegeli** [comment]
Please attach the Full Log File: http://pastie.org/pastes/new

No Log == No Support

**Comment by ShooterOS** [comment]
http://pastie.org/10925840 :-)

**Comment by Spegeli** [comment]
You should Upgrade to the newest Version.

**Comment by ShooterOS** [comment]
Thank you :)
