### ISSUE TITLE
Showing experience obtained after a number of attempts

### ISSUE THREAD

**Issue by KnightMirko** [Spegeli/PokemoGoBot-GottaCatchEmAll#273]
<a href='http://www50.zippyshare.com/v/2Rzl3l4E/file.html'><img src='http://www50.zippyshare.com/scaled/2Rzl3l4E/file.html' border='0' /></a>
After a number of attempts, the final message "CatchSuccess" does not show the amount of experience awarded.

**Comment by Spegeli** [comment]
Thx for Report, uploaded a new Version where the issue should be fixed ;-)

**Comment by KnightMirko** [comment]
Thank you so much!
