### ISSUE TITLE
Setup Visual Studio [HELP]

### ISSUE THREAD

**Issue by ibbatta** [Spegeli/PokemoGoBot-GottaCatchEmAll#274]
Hi all,

could you help me to setup visual studio (i use osx version) to run the project please? It could really appreaciate, thanks in advance

**Comment by Spegeli** [comment]
Sorry i dont give Support to Unix System.

**Comment by ibbatta** [comment]
Yes i know, i was asking for help to configure Visual Studio.
I think is the same if run on Unix or Win, isn't it?
