### ISSUE TITLE
Doing nothing but walking after hitting first Pokestop

### ISSUE THREAD

**Issue by Eddga** [Spegeli/PokemoGoBot-GottaCatchEmAll#278]
Since yesterday/today as soon as the bot hits the first Pokestop he stops catching pokemon and collecting items from Pokestops. Logging in and catching the pokemon which are around the spot where logged in correctly until first Pokestop is met. Then items are collected from this one only going on heading other Pokestops but neither collecting there items nor catching or meeting any Pokemon. Not even notified if there are any.
Using most recent version with GPX centralparkloop.gpx and updating via SVN and of course compiling again each time it updated.
Also verified if account is soft banned or anything and if everything is ok by logging in manually, catching some Pokemon and visiting Pokestops collecting items. Also tried varying walking speed and deleting Debug folder entirely which didn't help either.

![buggy](https://cloud.githubusercontent.com/assets/18622817/17298913/49660c52-580c-11e6-91d9-0414d548231d.PNG)

P.S.: Thanks for your unbelievable work on this project! Working really well so far. :+1:

**Comment by Pookiemon** [comment]
Mine seems to do the same thing=[

**Comment by Eddga** [comment]
Ah and just now I read about the tip:

Problem #2
Help! I'm not softbanned (still catching Pokemons) but I aren't getting any items from Pokesteops!
Solution
Your inventory is full, either tweak the inventory settings such that the highest possible number is below 350 or login to the game and recycle your unwanted items.

But mine isn't catching Pokemon, too, as already told.
And after realizing that in the last revision the "UseTeleportInsteadOfWalking"-Feature was integrated and defaulted to true I thought that was the problem. But disabling this one only helped for some time until hitting the first PokeStop again. :/

**Comment by Spegeli** [comment]
Your using GPX and UseTeleportInsteadOfWalking has nothing to do with GPX using.

GPX is currently a little broken and not recommend to use it.
