### ISSUE TITLE
Stop walking after 30-45min 

### ISSUE THREAD

**Issue by ryanalvin** [Spegeli/PokemoGoBot-GottaCatchEmAll#279]
Doing fine at first 30-45min, and then the program seems to stop working.
i need to close it first and rerun it again (kinda annoying)

it happen also at v2016.7.29.519.
i already trying using another pc, but same result again..

thank you bro ^^

**Comment by Spegeli** [comment]
2016.7.29 this was for 3 days...maybe you should update them?
