### ISSUE TITLE
the bot doesnt transfer any bots 

### ISSUE THREAD

**Issue by hexagon00** [Spegeli/PokemoGoBot-GottaCatchEmAll#280]
the bot doesnt transfer all the pokemons but it does transfer some of them. here is an ss of my usersettings.settings     i checked the list again and again i dont think i did anything wrong if i did forgive me and tell me pls :p
![untitled](https://cloud.githubusercontent.com/assets/20742833/17304158/dda76120-582c-11e6-882e-573d3d5c415a.png)

**Comment by h4rdboot** [comment]
try setting 'TransferPokemonKeepDuplicateAmount' to 1, it will then only keep 1 of each* (*see below), yours is set to keep 3.
'UseTransferPokemonKeepAboveCP' is set to true so it will keep any pokemon it finds above 1000CP (as set in 'TransferPokemonKeepAboveCP')

**Comment by Spegeli** [comment]
@h4rdboot said everything right ;-)
Try this and then it works fine ^^
