### ISSUE TITLE
no speeding down if teleport state false

### ISSUE THREAD

**Issue by goldenyears** [Spegeli/PokemoGoBot-GottaCatchEmAll#282]
dear team, 
can you add feature speeding down again to next version if we didn't use teleport, I think I still need speeding down feature because the bot always passes every come to pokestop 
![2016-08-02_035918](https://cloud.githubusercontent.com/assets/8521566/17305606/1f4ac23c-5866-11e6-8ade-4f37f843210a.jpg)

**Comment by Spegeli** [comment]
ähm there is a speed down option

````
                if (currentDistanceToTarget < 30 && speedInMetersPerSecond > SpeedDownTo)
                {
                    if (_client.Settings.DebugMode)
                        Logger.Write($"We are within 30 meters of the target. Speeding down to 10 km/h to not pass the target.", LogLevel.Navigation);
                    speedInMetersPerSecond = SpeedDownTo;
                }
````

**Comment by goldenyears** [comment]
well already check navigation, but I think because teleport feature, my character can't speeding down and passing pokestop to next one,
