### ISSUE TITLE
Constantly soft-banned from pokestops

### ISSUE THREAD

**Issue by LeafyDev** [Spegeli/PokemoGoBot-GottaCatchEmAll#283]
Very nice work so far.

However I seem to not be able to get items from pokestops with this, always getting the error message...

Things I've tried:

> - New account
> - Lower speed
> - Disabling teleport

Everything else works fine, but pokestops don't... which is kind of the whole point I'd like to use...

**Comment by Spegeli** [comment]
This can happen when the Server or this Region is currently unstable.

**Comment by LeafyDev** [comment]
Don't mind the occasional message in there, I added a few things but nothing that can break the gameplay.

http://pastie.org/private/1u6mh5qjoitkgotchynkyq

http://i.imgur.com/bGmIywg.png

**Comment by resident1206** [comment]
I had the same issue. I can exclude a soft-ban since it immediately works well after restart and the new soft ban unlocker is not working at all. Then I switched over to the default UserSettings.settings and just edited the logins and coordinates. This solved the problem for me: both Ptc and Google are working. I hope that info can help

**Comment by Alx666** [comment]
i'm u're 13th follower, i need support for batch configuration to make u code run easly on multiple accounts.. just allow username and password by commandline to override settings.
i can do it easly but u commit very often and is a pain.

**Comment by ryanalvin** [comment]
a tips from me: change your location

i also constantly get banned around 15 min when i roaming around central park manhattan (since theres alot of lure module at the park)

**Comment by LeafyDev** [comment]
Yeah i put it in a big city rather than small village and now working fine,
thanks all :D
