### ISSUE TITLE
EncounterNotFound & EncounterPokemonFled - Catch Pokemon

### ISSUE THREAD

**Issue by xquiaz** [Spegeli/PokemoGoBot-GottaCatchEmAll#286]
anyone know this problem ?

http://pastie.org/10926483

**Comment by maximoney1994** [comment]
yes had the same issue only with certain pokemons though. niantic tweaking stuff I guess

**Comment by rikka0w0** [comment]
Same problems here
Maybe Niantic has changed their API for some reasons?
I guess, perhaps the most likely reason is, their server is not very stable...

**Comment by finrdy** [comment]
me too. the program can't catch pokemons with this error
