### ISSUE TITLE
simple override for username and password from commandline

### ISSUE THREAD

**Issue by Alx666** [Spegeli/PokemoGoBot-GottaCatchEmAll#287]
I need to run u're code on multiple accounts from Rome, every time had to revert my changes.
A simple settings override would be appreciated..

PokemonGo.RocketAPI.Console -user1.xml
PokemonGo.RocketAPI.Console -user2.xml
PokemonGo.RocketAPI.Console -user3.xml

etc... just for make easy distribution of u're code

**Comment by Spegeli** [comment]
my bot dont support xml files and with the upcoming GUI there will be Multi Support.
