### ISSUE TITLE
(ATTENTION) Encounter problem: EncounterNotFound

### ISSUE THREAD

**Issue by rikka0w0** [Spegeli/PokemoGoBot-GottaCatchEmAll#290]
I'm using the latest version and I keep getting EncounterNotFound error when the program is trying to catch a pokemon. But sometimes this error won't occur and it can catch the pokemon successfully. Does any one have any ideas on this?

**Comment by finrdy** [comment]
me too. please tell me how to fix this?

**Comment by ryanalvin** [comment]
me too.. T.T

**Comment by rickyrsn** [comment]
me too . only can catch pidgey, ratata, zubat, poliwag, magnemit, maybe its random
[12:06:13] (INFO) Found 4 catchable Pokemon
[12:06:13] (ATTENTION) Encounter problem: EncounterNotFound
[12:06:13] (ATTENTION) Encounter problem: EncounterPokemonFled
[12:06:14] (ATTENTION) Encounter problem: EncounterPokemonFled
[12:06:14] (ATTENTION) Encounter problem: EncounterNotFound

**Comment by XiCynx** [comment]
@rickyrsn Just from looking at your log, I can tell you that the second and forth ones are from pokemon fleeing(like a softban or popped out of pokeball and fled). The first and last ones make me think that the bot thought there was pokemon there but then it wound up actually not finding it when it went to catch it? That's what I'm getting from it. I know Niantic are being bitches and making it harder to track pokemon.

**Comment by rikka0w0** [comment]
I want to contribute to this project, however I have limited ability to decode Niantic's protocol TAT
But I have made a functional console command handler, allows user to type and execute command such as "items list, pokemon list" in the console. I would like to merge my code into this project /w\

**Comment by rickyrsn** [comment]
@XiCynx but I can catch pidgey, ratata, zubat, poliwag, magnemit, but sometimes cant

**Comment by rikka0w0** [comment]
I have found a possible solution to this issus:
Set the walking speed to 20km/h and disable teleport function
Some function is missing in the latest version: slow down when approaching pokemon/pokestop

**Comment by rickyrsn** [comment]
@rikka0w0 yeah. I already setup this walking speed & turn off teleport, but still error

**Comment by rikka0w0** [comment]
I found a problem in code:
uncomment line 113 to line 120 in file Navigation.cs in package PokemonGo.RocketAPI.Logic

after this repair, it seems to work
I have set my speed to 50km per hour and teleporting is disabled

**Comment by rickyrsn** [comment]
@rikka0w0 ah, finally ! its work . thankyou

**Comment by Spegeli** [comment]
113 to 120 is already comment out?!
