### ISSUE TITLE
BUG Random location, already set but keep changing by itself using GPX

### ISSUE THREAD

**Issue by maliqoye** [Spegeli/PokemoGoBot-GottaCatchEmAll#291]
i got an error everytime using GPX, like there's a bug .. already set my location alti and longi to the place that i want .. but when program start it changing by it self...

here's my log using delimiter ( . )
http://pastie.org/10926550

and this one using delimiter ( , )
http://pastie.org/10926558

and this is my setting ...
https://cloud.githubusercontent.com/assets/14844774/17317197/401f6a0a-58a5-11e6-9b88-be2a46f39b11.jpg

**Comment by Spegeli** [comment]
GPX is bugged and not recommend to use it currently.
