### ISSUE TITLE
Multi bot update

### ISSUE THREAD

**Issue by KoooDT** [Spegeli/PokemoGoBot-GottaCatchEmAll#292]
I do not know whether such an interesting way of development.
So what has changed in the code to spread will not simply describe the essence of the modifications.
First of all I added array in the main console method. In this array I pass 3 parameters when you start the console: AuthType, Login, Pass.
respectively, in the class Settings to override the settings for the interface ISettings;
Then he formed a global path for all folders with logs in the global constant, which is determined by: 
> Path.Combine(Directory.GetCurrentDirectory(), $"pokemongo_{ PtcUsername }")
or
> Path.Combine(Directory.GetCurrentDirectory(), $"pokemongo_{ GoogleEmail.Substring(0, GoogleEmail.IndexOf("@"))}")

All methods changed jobs on this variable.

What I got in the end. In the folder where I will run the bot, there is one folder with the release. The higher-level folder I added a text file in which each line contains the authentication type, login and password.
Also in the folder above the level lies bat file, which reads all logins and launches the console under each bot, passing it to the input of a login and password.

For each instance of creates a folder with logs. Thus bot code itself is in the same folder, and the result of his work (the logs themselves) are in separate folders.
All boats in this case are the same config file and the same source. This is convenient for me, because I periodically add something new in the code, and to update the bot in each folder I was not comfortable.

**Comment by KoooDT** [comment]
Tell me does this method is interesting for the development of a bot or not?

**Comment by Spegeli** [comment]
With the upcoming GUI, there will be Multi Support.
