### ISSUE TITLE
 (ERR) Got an exception, trying automatic restart..

### ISSUE THREAD

**Issue by madsmessi2** [Spegeli/PokemoGoBot-GottaCatchEmAll#297]
After that it just restarting and do it again. HELP

**Comment by Gonekaka** [comment]
same problem here :/ 
please help

**Comment by Gonekaka** [comment]
![screenshot_12](https://cloud.githubusercontent.com/assets/20794179/17327911/d9f3713c-58e4-11e6-9f56-e6235b109069.png)

**Comment by Bakeneko** [comment]
Probably just a temporary issue with google authentication server ?

**Comment by Spegeli** [comment]
Thats what i think too.

**Comment by juanova** [comment]
can help at my PC bot dosent work :(

**Comment by madsmessi2** [comment]
So you mean that it will work again soon?

**Comment by Spegeli** [comment]
For me and most other users google is working currently fine.

**Comment by Babiguling** [comment]
Hi brother.. I also hv same issue. Login using ptc is fine,, but show error when using google.. Any advice?? Thanks anyway
