### ISSUE TITLE
InventoryPokemonFull

### ISSUE THREAD

**Issue by OhhPian** [Spegeli/PokemoGoBot-GottaCatchEmAll#298]
I just create new account and i go straight play with bot without any tutorial, now my pokemon inventory is full 250/250. I cant go to my pokemon inventory since i need to complete my tutorial first. Anyone have idea how to get rid some pokemon so i can complete the tutorial ?

**Comment by Spegeli** [comment]
Currently the only Solution is to Evolve & Transfer some via the UserSettings.
