### ISSUE TITLE
[Request] Max # of collection 

### ISSUE THREAD

**Issue by Shakazan** [Spegeli/PokemoGoBot-GottaCatchEmAll#306]
Currently we have filters on each item in the inventory
E.g. Pokeballs => max 20, Greatballs => max 50 etc.

However I am having issues when I do a GPX route and I'm not hitting a lot of pokestops that I start running out of balls.  When I look at my inventory I see that while I have 0 ultraballs, greatballs etc. I am still discarding standard Pokeballs.

It would be useful to be able to say something along the lines of:
MaxBalls = 150
BallPriority = ItemId.ItemMasterBall, ItemId.ItemUltraBall, ItemId.ItemGreatBall, ItemId.ItemPokeBall
That way I could have an inventory of 150 pokeballs if I didn't have any other types, but as soon as I did get any Great or Ultra balls then those would be retained and the lower value balls would be recycled

**Comment by xxsteven69xx** [comment]
I would say keep 150 of all ball types, when limit is hit recycle lowest tier item; eg pokeballs then great balls then ultraball in that order.

**Comment by xxsteven69xx** [comment]
same with potions

**Comment by XiCynx** [comment]
This fits in as a request to enhance a current feature. Marked as Enhancement and will let Spegeli decide.

**Comment by Spegeli** [comment]
Added to the latest Release: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/6a691f238dc59b353012573f48bb776b3e1aea11
