### ISSUE TITLE
error:  You don't own any Pokeballs :( 

### ISSUE THREAD

**Issue by frager45** [Spegeli/PokemoGoBot-GottaCatchEmAll#307]
Pic: http://i.hizliresim.com/GzdDpV.png

need help....

**Comment by Spegeli** [comment]
yeah because your item bags are full ^^ so he can't get new pokeballs from pokestops and then you get this message

**Comment by frager45** [comment]
not full, i look my bag but my hero not go pokestop.
i try diffrent coordinats but not going at pokestop

**Comment by frager45** [comment]
129/350 my bag
127/230 my pokemon
