### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DexonPlus** [Spegeli/PokemoGoBot-GottaCatchEmAll#309]
Hey buddy, you BOT is really awesome, I just have one doubt:

When you set the coordinates and the maximum distance to walk, it means that you will moving a round in a circle?, is the maximum distance the radius or the diameter of the circle?.

Sorry for bother you, but it will help me a lot to understand a little bit your work.

Thanks for all your effort

**Comment by Spegeli** [comment]
MaxTravel is the Radius Distance to the Default Long & Lat
