### ISSUE TITLE
[Request - Suggestion] - More RANDs for walking/running/driving between stops to act more humanish

### ISSUE THREAD

**Issue by Goatboy1971** [Spegeli/PokemoGoBot-GottaCatchEmAll#310]
if the stops are relatively close (Under 150m), then have the bot move at a random double between 5.00 - 9.99 while traveling to the next point.

if the next target location is over 150m, then have the bot move at a random double 35.00 to 49.99 to the next point

This would simulate a more human interaction with the server, as not everyone moves at a set speed for hours at a time while walking or running around.  Humans would walk when the distance is short and would hop in a auto/bike when the distance are far.

**Comment by KnightMirko** [comment]
In similar fashion, it would be more "humanish" to randomize delays between actions such as catching pokemon or visiting nearby pokestop. Such settings may be optional - to either make botting more humanlike or efficient.

**Comment by Spegeli** [comment]
Humiazer is useless, Niantic detects us anyway as bot.
