### ISSUE TITLE
Object reference not st to an instance of an object. from PokemonGo.PocketAPI.Logic

### ISSUE THREAD

**Issue by Azhy** [Spegeli/PokemoGoBot-GottaCatchEmAll#313]
![1b957fd4e1009b22174e703b9a0f1be3](https://cloud.githubusercontent.com/assets/20723849/17348365/a691f3b2-590d-11e6-8deb-5b3f8e622448.png)
![aaf6c38a10d22a5fd3da106baceb4b6d](https://cloud.githubusercontent.com/assets/20723849/17348372/ab8bb40c-590d-11e6-9634-cdc8f92b50e8.png)

**Comment by Spegeli** [comment]
Seems Server currently unstable.
When the issue exists tomorrow, i will take a deeper look.
