### ISSUE TITLE
No usable Pokestops nearby?!?

### ISSUE THREAD

**Issue by Kaffetjuven** [Spegeli/PokemoGoBot-GottaCatchEmAll#316]
![untitled](https://cloud.githubusercontent.com/assets/20623075/17464964/b294fce6-5cea-11e6-8476-0615b9abfe7e.png)
AM i missing something important here ? I've run the bot multiple times before but after 2 days of not botting this came when i tried to start the bot with the old version and the new. Same coordinates that i've used before where its lots of pokestops. Any suggestions ? Cheers

**Comment by Spegeli** [comment]
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll#a-pokemon-go-bot-based-on-feroxrevs-api
