### ISSUE TITLE
[REQUEST] Keep pokemon based on moveset

### ISSUE THREAD

**Issue by ellm62** [Spegeli/PokemoGoBot-GottaCatchEmAll#317]
Reference a CSV file for best movesets (offence or defence).

If CP > X then Keep
   If Moveset != BestOffenceMoveset || BestDefenceMoveset then Transfer
If IV > X then Keep
   If Moveset != BestOffenceMoveset || BestDefenceMoveset then Transfer

**Comment by kevinmp97** [comment]
Unable to copy file "obj\Debug\PokemonGo.RocketAPI.Console.exe" to "bin\Debug\PokemonGo.RocketAPI.Console.exe". Access to the path 'obj\Debug\PokemonGo.RocketAPI.Console.exe' is denied.	PokemonGo.RocketAPI.Console			
i cant seem to run the bot, is there any ideas how do to fix this?

**Comment by Kongolan** [comment]
You can only make a file, which has the proper data for all pokemon and movesets, else it would be too much work for the developer... Also finding a high CP + good IV + perf Moveset is so rare, that you will basically transfer everything...
