### ISSUE TITLE
can not upload dll “encrypt.dll"  From HRESULT:0x8007007E 

### ISSUE THREAD

**Issue by PokemonGogogo** [Spegeli/PokemoGoBot-GottaCatchEmAll#318]
Hi, it's really great to see the bot working again.
However, when I run the bot, it appears, can not upload dll “encrypt.dll"  From HRESULT:0x8007007E 
Do you know what's wrong with that?
Thanks!

**Comment by Spegeli** [comment]
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll#a-pokemon-go-bot-based-on-feroxrevs-api

**Comment by PokemonGogogo** [comment]
Thank YOU!!!!!

**Comment by audiophile26** [comment]
Pokemongogo would you pm me how im to find this dll file on my pc?

**Comment by PokemonGogogo** [comment]
You can try to get in the chat room. There is so much useful information

**Comment by audiophile26** [comment]
I dont have permission to view the chat in discord

**Comment by audiophile26** [comment]
Is that the chat you are talking about?

**Comment by PokemonGogogo** [comment]
There is one link just under the code resource. Did you find it? At the beginning of the update notice
