### ISSUE TITLE
Unable to load dll 'encrtypt.dll'

### ISSUE THREAD

**Issue by safarla2** [Spegeli/PokemoGoBot-GottaCatchEmAll#325]

**Comment by KoooDT** [comment]
... Did you read update?

**Comment by LIMBO199** [comment]
how to get that dll?

**Comment by Spegeli** [comment]
https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll#a-pokemon-go-bot-based-on-feroxrevs-api
