### ISSUE TITLE
Pokemon go rocket api ( nothing comes up when opening)

### ISSUE THREAD

**Issue by infamouslouis** [Spegeli/PokemoGoBot-GottaCatchEmAll#331]
I downloaded the new version of the bot today, previous versions work fine and i have a toolbar for user settings etc... It may be i'm just a noob with visual stuido

https://postimg.org/image/htav5n6md/bf99f3cc/

**Comment by LIMBO199** [comment]
follow the steps : https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/wiki

**Comment by Spegeli** [comment]
For Help pls use the Support on our Discord Server: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/wiki/Chat-&-Rules#chatting-using-discord
