### ISSUE TITLE
The thread 0x...... has exited with code 0 (0x0)

### ISSUE THREAD

**Issue by flaviorighi** [Spegeli/PokemoGoBot-GottaCatchEmAll#335]
Sometimes a sequence of thread exited with 0 and the console freeze until I press ctrl+c.
When it's freezed and I press ctrl+c the console not close but just unlock and continue normally, as you see in the image.
![cattura](https://cloud.githubusercontent.com/assets/16403175/17498853/2e34d5c6-5dca-11e6-8a0d-c648bf814370.PNG)

**Comment by XiCynx** [comment]
You sure you got the right bot?  This looks nothing like ours?  What kind of console you running this through?

**Comment by JonathanBourassa** [comment]
XiCynx this is not the Console output. It's the output window of Visual studio, bottom left:
![output](https://cloud.githubusercontent.com/assets/6863730/17500691/be1ef920-5da5-11e6-9394-37b6cd05c097.png)

**Comment by flaviorighi** [comment]
yes, it is the output in diagnostic tools inside VS, it's the only thing that I notice something when it freeze
![cattura](https://cloud.githubusercontent.com/assets/16403175/17500754/7a58aec4-5dd8-11e6-90bc-f186d1c82d98.PNG)

**Comment by JonathanBourassa** [comment]
I really think is just the thread exiting when Pogo servers are getting unstable. I'll Let Spegeli confirm that.

**Comment by flaviorighi** [comment]
It happens randomly not only when servers are unstable.
And for sure I can't stabilize the servers from my home with a process
kills (ctrl+c).

It's like to looping while waiting the lost thread or something like this.

Il 09 ago 2016 02:27, "Lorien" <notifications@github.com> ha scritto:

**Comment by exverse** [comment]
This output message is just program's garbage collection. It is closing a thread what was open to execute a procedure. This is nothing to worry about, it is normal. You might have some kind of strict debugging active in your solution.
