### ISSUE TITLE
[Request] Bot to stay in one location, without going to pokestops

### ISSUE THREAD

**Issue by superpitzi2** [Spegeli/PokemoGoBot-GottaCatchEmAll#337]
Sometimes you can find 3-5-6 lure at one place and it would be great if the bot wont go anywhere. just to stay there and get the pokemons from that lure
evolve/transfer/get

Thanks

**Comment by Napcazz** [comment]
if you want that you can make distance 0 - 10

**Comment by XiCynx** [comment]
As Napcazz said, just lower your walking distance and you'll only move around to those specific ones.
