### ISSUE TITLE
(ERROR) Unhandled exception: System.Configuration.SettingsPropertyNotFoundException: The settings property 'My Coordinates Here' was not found.

### ISSUE THREAD

**Issue by Whostuck** [Spegeli/PokemoGoBot-GottaCatchEmAll#342]
It's giving me this message for my latitude and longitude when I use a decimal or a comma in the coordinates. Side note: I'm a n00b. Any suggestions? Help would be greatly appreciated. Thanks.

**Comment by TaeTae01** [comment]
sorry sir
how to config latitude and longtitude
thank

**Comment by minipouss83** [comment]
look my tuto:
![tuto1](https://cloud.githubusercontent.com/assets/20757898/17525945/59b6031e-5e65-11e6-9d8d-bda7cd55a177.jpg)
![tuto2](https://cloud.githubusercontent.com/assets/20757898/17525944/59b2800e-5e65-11e6-8ff2-82ddf433b649.jpg)
![tuto3](https://cloud.githubusercontent.com/assets/20757898/17525946/59caade6-5e65-11e6-8cb7-93263073f736.jpg)

**Comment by TaeTae01** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20931390/17526518/c42020dc-5e91-11e6-84e6-d69c0314be61.jpg)

I  do anything like you sir but when i run BOT I have same problem again
thank for your help

**Comment by Spegeli** [comment]
@TaeTae01 This is working correct. Just wait longer then the 15 Seconds and you will see it.

**Comment by TaeTae01** [comment]
OK it run but new problem
Sorry to disturb
![untitled](https://cloud.githubusercontent.com/assets/20931390/17526687/82a375c2-5e92-11e6-897f-a852b5ac7c9f.jpg)

**Comment by Spegeli** [comment]
Login Details Wrong or PTC Servers down.

**Comment by qhutilizer** [comment]
im having this issue
anyone can help?
![issues](https://cloud.githubusercontent.com/assets/20706802/17529560/fac6e68c-5e9d-11e6-9fea-71fd0ed5ed70.png)

**Comment by XiCynx** [comment]
@qhutilizer Read the included ReadMe dude... the answer is right in there for what you need to do to get this up and going without getting that error.
