### ISSUE TITLE
(ERROR) program just looping at starting again in 10 seconds. . .

### ISSUE THREAD

**Issue by toroageito** [Spegeli/PokemoGoBot-GottaCatchEmAll#343]
![untitled](https://cloud.githubusercontent.com/assets/20931857/17525196/ddc18c8e-5e8b-11e6-899d-9d18085e2d61.jpg)

It's like the program not run at all.
it's keep saying starting again in 10 seconds. . .

**Comment by Spegeli** [comment]
This is not my Bot Version...
