### ISSUE TITLE
Keep Duplicate Pokemon feature is missing

### ISSUE THREAD

**Issue by rakyat94** [Spegeli/PokemoGoBot-GottaCatchEmAll#349]
First i want to Thank you Spegeli you made an Awesome PoGo Bot.
It's so easy to use if you follow the instructions

In the last update i notice that there is no "TransferPokemonKeepDuplicateAmount" in UserSettings
So i reread "ReadMe" and it say that KeepDuplicate default amount is 2 so i think there is no problem. 
But when i opened PoGo App There is only one Pokemon of each Pokemon type.
would you like to bring it back? please

sorry for my bad english
btw thank you

**Comment by XiCynx** [comment]
The ReadMe needs to be updated.  But in the release notes it states that there are now two options instead as that one was removed.  You now need to select TransferPokemonKeepAmountHighestCP and TransferPokemonKeepAmountHighestIV instead.

**Comment by rakyat94** [comment]
Thank You dude
