### ISSUE TITLE
no pokestop or pokemon

### ISSUE THREAD

**Issue by qhutilizer** [Spegeli/PokemoGoBot-GottaCatchEmAll#354]
i think i got ip banned by pogo..i tried using phone connection and i can see pokestop and pokemon or gym, but when i tried to connect with wifi there are no pokestops,pokemon or gym.. its just empty blank map. does it mean i got ip banned by pogo?any1 can help me with this?

**Comment by Spegeli** [comment]
Is Discord if you need Help: https://discord.gg/KzJUjDE
