### ISSUE TITLE
CSV file : Seperate columns for CP and MaxCP

### ISSUE THREAD

**Issue by briantsang** [Spegeli/PokemoGoBot-GottaCatchEmAll#355]
Separating the CP and MaxCP will allow the user to sort pokemon by CP.  

These would be the two changes required in Inventory.cs ExportPokemonToCs() function

const string header = "PokemonID,Name,NickName,Level,**CP,MaxCP**,IV Perfection in %,Attack 1,Attack 2,HP,Attk,Def,Stamina,Familie Candies,IsInGym,IsFavorite,previewLink";

 string contentPart2 = $"**,\"{pokemon.Cp}\",\"{PokemonInfo.CalculateMaxCp(pokemon)}**\",";

**Comment by Spegeli** [comment]
Added to the next Release.
