### ISSUE TITLE
Separate CP and MaxCP columns in Pokelist Export to CSV file.

### ISSUE THREAD

**Issue by Shakazan** [Spegeli/PokemoGoBot-GottaCatchEmAll#358]
The file exported to CSV combines CP and MaxCP columns.  
When I open this file in Excel, I cannot sort it by MaxCP.

Please separate CP and MaxCP columns

P.S. The fix is on these two lines:
const string header = "PokemonID,Name,NickName,Level,CP,MaxCP,IV Perfection in %,Attack 1,Attack 2,HP,Attk,Def,Stamina,Familie Candies,IsInGym,IsFavorite,previewLink";
                    
string contentPart2 = $",{pokemon.Cp},{PokemonInfo.CalculateMaxCp(pokemon)},";

**Comment by Spegeli** [comment]
See https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/355
