### ISSUE TITLE
lvlup bug report

### ISSUE THREAD

**Issue by Napcazz** [Spegeli/PokemoGoBot-GottaCatchEmAll#361]
![silincek](https://cloud.githubusercontent.com/assets/20713280/17575116/4a261794-5f6f-11e6-847e-a1e00a2b6c61.png)

It will say i need 7m exp but i need 5m to lvl up

**Comment by tizaro1** [comment]
nasil indireces haci ?_

**Comment by tizaro1** [comment]
how to download help pls.

**Comment by XiCynx** [comment]
Confirmed bug, level 40 experience needed is 5,000,000, not 7,000,000.

**Comment by Napcazz** [comment]
and my current exp is have to be 2m not 4m :/

**Comment by Spegeli** [comment]
Should be fixed with the next version.
