### ISSUE TITLE
Level up bug in real game

### ISSUE THREAD

**Issue by 30er** [Spegeli/PokemoGoBot-GottaCatchEmAll#363]
hi guys
found out that niantic hides the level up button for pokemons that reached lvl 38.5
and yes i checked it more times ;) and no its not just disabled!
im lvl 39 now and run on iOS
and through api i could lvl up to 39.5
its maybe a good idea to implement the "bug" also in bot... so they cant detect lvl up through bots

**Comment by Spegeli** [comment]
there are other ways for niantic to detect us ^^
