### ISSUE TITLE
An error occurred while sending the request. from mscorlib

### ISSUE THREAD

**Issue by divyeshpatel111** [Spegeli/PokemoGoBot-GottaCatchEmAll#367]
![problem](https://cloud.githubusercontent.com/assets/7437138/17596746/752dac8a-6010-11e6-87a8-89bbbec40bd3.png)

How to resolve it...??

**Comment by Makto94** [comment]
![image](https://cloud.githubusercontent.com/assets/20729264/17602515/3c77e07a-600d-11e6-8f5a-4caa720ce79c.png)

How i can resolve it?

**Comment by Makto94** [comment]
UserSetting-->AuthType change in Google

**Comment by divyeshpatel111** [comment]
But I have Ptc Account So I Need to login as Ptc Account.
So I Config As It Ptc.
