### ISSUE TITLE
Object Reference not set to an instance of an object from PokemonGo.RocketAPI.Logic

### ISSUE THREAD

**Issue by B14CKD24G0N** [Spegeli/PokemoGoBot-GottaCatchEmAll#371]
![error](https://cloud.githubusercontent.com/assets/11536081/17613912/3a6d5f88-608c-11e6-8e86-488433ae0ba9.png)

Suddenly just now, i can't run it. Thanks.

**Comment by filippofavaro** [comment]
Same problem noticed about 4 hours ago. Also QuickSpin (unban bot) is not working, maybe Niantic has made some changes?

**Comment by Spegeli** [comment]
Yeah seems niantic changes something the last night.
But currently i cant say what.
