### ISSUE TITLE
pokemon with > [value] of CP = keep , can i do that ?

### ISSUE THREAD

**Issue by umaysven** [Spegeli/PokemoGoBot-GottaCatchEmAll#372]
recently i got some pokemon that have  > 1000 CP,
but my best pokemon just have 700 CP and less @.@
i want to keep them but its just gone --aaaa :(

maybe u can add a little config based on CP,
ex :
minCPtoKeep=1000;

thats just my idea :D

**Comment by Spegeli** [comment]
Sorry there are currently enough Options for Transfer:

1) All Pokemons in Gyms and marked as Favorite are Ignored
2) TransferPokemonKeepAllAboveCPValue = He will keep ALL Pokemon above this Value
