### ISSUE TITLE
[Request] Random speed after pokestops

### ISSUE THREAD

**Issue by superpitzi2** [Spegeli/PokemoGoBot-GottaCatchEmAll#375]
Usually a normal person would not drive at the same speed every time it take a pokestop, so it would be best with a randomize to speed, also to the balls, not to be every time perfect.
To be more as human :)

**Comment by Spegeli** [comment]
I don't think that Humanizer things will prevent us from banns, but i added it already to my local version.
Will be available with the next release.

**Comment by superpitzi2** [comment]
Idea is if we move too fast to USA to Japan and stuff that ban will come, if you go and STAY in one place, the ban wont come for sure. I did with 4 accounts now. and still all live and i did not had a soft ban once.
