### ISSUE TITLE
No Usable Pokestops?!

### ISSUE THREAD

**Issue by ia7maxd** [Spegeli/PokemoGoBot-GottaCatchEmAll#377]
Every time i try to run the bot it says no usable pokestops, I tried to change the latitude and longitude but nothing changed!

any solutions? 

[12:05:32] (ATTENTION) No usable PokeStops found in your area. Reasons: Softbann
ed - Server Issues - MaxTravelDistanceInMeters too small

**Comment by WithoutSkil** [comment]
Stop botting for a few hours. Go play outside or  sleep or whatever and then try again.

**Comment by ManWoo** [comment]
Now I can find pokestops,but nothing can collect and no XP get too

**Comment by ia7maxd** [comment]
@WithoutSkil Waited 4  hours didn't :(

**Comment by XiCynx** [comment]
Guys, it literally tells you right in the dialog what the reason are.
Reasons: Softbanned - Server Issues - MaxTravelDistanceInMeters too small

How much more do we have to point this out to you.

**Comment by ia7maxd** [comment]
@XiCynx Bro but i tried everything and im sure that im not Softbanned and i changed the place couple of time

**Comment by XiCynx** [comment]
Bans have been last up to 16-24 hours from certain users experiences.  There is also a good chance that you are IP banned which means you need to use a proxy to play on that account now.

**Comment by ia7maxd** [comment]
i tried different bots and it works the problem wih the bot not my account
