### ISSUE TITLE
Inventory clearing issues

### ISSUE THREAD

**Issue by 0logic0** [Spegeli/PokemoGoBot-GottaCatchEmAll#381]
I'm probably overlooking something. Yesterday I started getting an issue where items are not removed from inventory. I get the "you don't own any pokeballs" message. I tried editing inventory values in settings.cs. I tried a new installation and I have the same issue.  I tried as many things as I could think of. Thanks for any help

I logged into the account and looks like it stops collecting items from poke stops, doesn't seem like a ip or soft ban being as soon as I logged back in with the bot after logging in on a device with a proxy it works perfect... if it sounds like a soft ban let me know, I just haven't seen any of the definitive signs.

**Comment by wowsuchdeveloper** [comment]
Looks like soft ban symptoms.

**Comment by Spegeli** [comment]
Then your Softbanned.
