### ISSUE TITLE
[REQUEST ACCEPTED] Multi Account

### ISSUE THREAD

**Issue by myfirstevercode** [Spegeli/PokemoGoBot-GottaCatchEmAll#66]
Is it possible to launch different account in 1 exe but reading different kind of accounts

Inside the folder you put your accounts like
google1
google2
google3

then run orig.exe and it will automatically launch copy and accounts

orig1.exe
orig2.exe
orig3.exe

so far im running a batch file just to rune 3 bots for me and my family.. thanks

**Comment by Spegeli** [comment]
Multi Account is planned with the upcoming GUI, but currently there is no ETA.
