### ISSUE TITLE
[Request] two tier [KeepMinDuplicatePokemon]

### ISSUE THREAD

**Issue by angilinwago** [Spegeli/PokemoGoBot-GottaCatchEmAll#67]
firstly thank you so much for your fantastic work, you are truly a genius
now I am into the higher level of the game, there are some monsters I want to keep more and some monsters I want to get rid of.
is it possible to have a two tier [KeepMinDuplicatePokemon],
so you can automatically have for example 6 best eevees/dratinis, whereas only 1 golbats/zubats
thanks

**Comment by angilinwago** [comment]
extension of this tier system could also be the temporary solution to the IV vs CP problem, this way the minimal IV and CP can be applied only to top tier rare monsters of one's choosing.

**Comment by Spegeli** [comment]
you can mark your pokemons as favorite, then they will be ignored for transfer.
