### ISSUE TITLE
[ISSUE CONFIRMED] Requesting GetInventoryResponse lets the bot sometimes relog/crash

### ISSUE THREAD

**Issue by zhuchentiancai** [Spegeli/PokemoGoBot-GottaCatchEmAll#73]
Can you add a function that the programm will automatically restart when it is crashed? Sometimes it is crashed and Visual Studio shows the line which causes the crash, like "getInventoryInfo" or something like that.
Thx

**Comment by Navyguy330** [comment]
I use a batch file that checks to see if the .exe is in the task manager and if not (every 10 mins) it restarts them all.

**Comment by Spegeli** [comment]
Yeah currently i investigate at the getInventory Info relog/crash. 
I think this comes from a bad server response and i hope i can fix this within the next 24 hours, so there will be no crash anymore ^^

**Comment by DangersClose** [comment]
@Navyguy330 can you give me a copy of this that i can use?
