### ISSUE TITLE
[ISSUE] Transfer exception

### ISSUE THREAD

**Issue by renegade221** [Spegeli/PokemoGoBot-GottaCatchEmAll#94]
![213](https://cloud.githubusercontent.com/assets/20684436/17178266/7537e38e-541d-11e6-9053-842cc4580877.png)
i get this every time the bot transfers... what should i do ?

**Comment by Spegeli** [comment]
Please try the latest Version and let me know if this issue still exists.

**Comment by XiCynx** [comment]
Same as here, please check and report in this thread.

https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/issues/101
